package wgr.impl;

// GENERATED by tools/gen_raw.py from wgrender's include/*.h — do not edit.
// Re-run the tool when wgrender's API moves; it writes this file whole.
//
// wgrender 0.0.1 at ec8b8e1-dirty, 34 headers.
// wgrender-headers: a4a9884e6b729dc6

/** What `wgr.Version` compares the running library against. **/
class BuiltVersion {
	public static inline final MAJOR = 0;
	public static inline final MINOR = 0;
	public static inline final PATCH = 1;
	public static inline final STRING = "0.0.1";

	/** The wgrender commit these were generated from, when there was one. **/
	public static inline final COMMIT = "ec8b8e1-dirty";

	/** A digest of the headers; `tools/gen_raw.py --check` compares it. **/
	public static inline final HEADERS = "a4a9884e6b729dc6";
}
