#!/usr/bin/env python3
"""Generate src/fonts/sk_default_font.h: libsk's built-in font, an ASCII subset of
JetBrains Mono (examples/assets/fonts/JetBrainsMono, SIL Open Font License 1.1; see
src/fonts/JetBrainsMono-OFL.txt) embedded as a byte array.

Needs fontTools (`pip install fonttools`). Run from anywhere:
    tools/gen_default_font.py
"""
import io
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "examples/assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf")
OUTPUT = os.path.join(ROOT, "src/fonts/sk_default_font.h")

options = subset.Options()
options.hinting = False            # fontstash rasterizes without hinting
options.desubroutinize = True
options.layout_features = []       # no ligatures or kerning tables fontstash doesn't use
options.name_IDs = ["*"]           # keep the copyright and license records (OFL)
options.drop_tables += ["GSUB", "GPOS", "GDEF", "kern", "DSIG"]

font = TTFont(SOURCE)
subsetter = subset.Subsetter(options)
subsetter.populate(unicodes=range(0x20, 0x7F))  # printable ASCII
subsetter.subset(font)
buffer = io.BytesIO()
font.save(buffer)
data = buffer.getvalue()

lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
with open(OUTPUT, "w") as out:
    out.write("/* Generated by tools/gen_default_font.py; don't edit.\n")
    out.write(" *\n")
    out.write(" * libsk's built-in font: JetBrains Mono Regular, subset to printable ASCII\n")
    out.write(" * (U+0020-U+007E), without hinting or layout tables.\n")
    out.write(" * Copyright 2020 The JetBrains Mono Project Authors\n")
    out.write(" * (https://github.com/JetBrains/JetBrainsMono), licensed under the SIL Open Font\n")
    out.write(" * License, Version 1.1: src/fonts/JetBrainsMono-OFL.txt. */\n")
    out.write("#ifndef SK_DEFAULT_FONT_H\n#define SK_DEFAULT_FONT_H\n\n")
    out.write(f"static const unsigned char sk_default_font_ttf[{len(data)}] = {{\n")
    for line in lines:
        out.write(f"    {line},\n")
    out.write("};\n\n#endif // SK_DEFAULT_FONT_H\n")
print(f"gen_default_font: {len(data)} bytes -> {os.path.relpath(OUTPUT, ROOT)}", file=sys.stderr)
