/* Generate src/data/wgr_brdf_lut.h: the split-sum BRDF table image-based lighting reads
 * (scale and bias of F0 by n.v and roughness), computed once here instead of at every
 * startup (tens of milliseconds of CPU at init, more on a phone). It's the same
 * function the library would run (wgri_environment_brdf_lut), linked from the headless
 * library, written as half floats: an RG16F texture uploaded as is.
 *
 *   cmake --build --preset headless --target gen-brdf-lut   (builds this, and runs it)
 *
 * tests/unit/environment_test.c checks the table matches the function. */
#include <stdio.h>
#include <stdlib.h>

#include "internal/wgr_environment_internal.h"

int main(int argc, char **argv)
{
    const int n = WGRI_ENVIRONMENT_LUT_SIZE;
    const char *path = argc > 1 ? argv[1] : "src/data/wgr_brdf_lut.h";
    float *lut = malloc(sizeof(float) * (size_t)n * n * 2);
    FILE *out = fopen(path, "w");

    if (lut == NULL || out == NULL) {
        fprintf(stderr, "gen_brdf_lut: can't write %s\n", path);
        return 1;
    }
    wgri_environment_brdf_lut(n, WGRI_ENVIRONMENT_LUT_SAMPLES, lut);
    fprintf(out, "/* Generated by tools/gen_brdf_lut.c (the gen-brdf-lut target): don't edit. The split-sum BRDF\n"
                 " * table, %dx%d, %d samples a texel: half floats, (scale, bias) for n.v = (x + 0.5) / %d\n"
                 " * across and roughness = (y + 0.5) / %d down. */\n",
            n, n, WGRI_ENVIRONMENT_LUT_SAMPLES, n, n);
    fprintf(out, "#ifndef WGR_DATA_BRDF_LUT_H\n#define WGR_DATA_BRDF_LUT_H\n\n#include <stdint.h>\n\n");
    fprintf(out, "static const uint16_t wgr_brdf_lut[%d * %d * 2] = {\n", n, n);
    for (int i = 0; i < n * n * 2; i++) {
        fprintf(out, "%s0x%04x,%s", i % 12 == 0 ? "    " : "", wgri_environment_half_from_float(lut[i]),
                i % 12 == 11 || i == n * n * 2 - 1 ? "\n" : " ");
    }
    fprintf(out, "};\n\n#endif // WGR_DATA_BRDF_LUT_H\n");
    fclose(out);
    free(lut);
    printf("wrote %s\n", path);
    return 0;
}
