#include "sk_environment.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "data/sk_brdf_lut.h"
#include "internal/exports.h"
#include "internal/sk_camera3d.h"
#include "internal/sk_environment.h"
#include "internal/sk_handle_pool.h"
#include "internal/sk_loader.h"
#include "internal/sk_render.h"
#include "sk_logger.h"

#include "stb_image.h"

/* generated by sokol-shdc from src/shaders/sk_model.glsl (the background program) */
#include "internal/sk_shaders.h"

#define ENVIRONMENTS_INITIAL 8 /* slots to start with; the pool doubles as needed */
#define MIN_SOURCE_CUBE_SIZE 64   /* the source cubemap matches the image: width / 4 per face, */
#define MAX_SOURCE_CUBE_SIZE 1024 /* rounded down to a power of two */
#define PREFILTER_SAMPLES 96
#define MAX_BACKGROUND_DRAWS 32   /* per frame */
#define PI_F 3.14159265358979f

/* Environment resource: the prefiltered cubemap on the GPU and its irradiance. */
typedef struct {
    sg_image cube;            /* prefiltered for lighting: mip = roughness */
    sg_view cube_view;
    sg_image background;      /* the image at its own resolution, box-filtered mips (for blur) */
    sg_view background_view;
    int background_mip_count;
    sk_env_sh_t sh;
    int ref_count;
    char path[256];
    bool has_path;
} sk_environment_t;

typedef struct {
    sk_mat4_t inv_view_proj;
    sk_handle_t environment;
    float lod;
    float intensity;
    float rotation;
    int tonemap;
    float exposure;
} sk_background_draw_t;

static sk_environment_t *sk_environments; /* grown by the pool: don't hold a pointer across a create */
static sk_handle_pool_t sk_environment_pool;

static struct {
    bool ready;
    sg_image lut;
    sg_view lut_view;
    sg_image black_cube;
    sg_view black_cube_view;
    sg_sampler cube_sampler;
    sg_sampler lut_sampler;
    sg_shader background_shader;
    sg_pipeline background_pipeline;
    sg_buffer background_triangle;
    sk_background_draw_t backgrounds[MAX_BACKGROUND_DRAWS];
    int background_count;
} sk_env;

/* ================================================================ CPU ==== */

static inline float clamp01(float x) { return x < 0.0f ? 0.0f : (x > 1.0f ? 1.0f : x); }

vec3_t sk_environment_equirect_dir(float u, float v)
{
    const float phi = (u - 0.5f) * 2.0f * PI_F;
    const float theta = v * PI_F;
    return (vec3_t){sinf(theta) * sinf(phi), cosf(theta), -sinf(theta) * cosf(phi)};
}

void sk_environment_dir_equirect(vec3_t dir, float *u, float *v)
{
    const vec3_t d = sk_v3_norm(dir);
    *u = 0.5f + atan2f(d.x, -d.z) / (2.0f * PI_F);
    *v = acosf(d.y < -1.0f ? -1.0f : (d.y > 1.0f ? 1.0f : d.y)) / PI_F;
}

vec3_t sk_environment_cube_dir(int face, float s, float t)
{
    const float sc = 2.0f * s - 1.0f, tc = 2.0f * t - 1.0f;
    vec3_t d;
    switch (face) {
        case 0: d = (vec3_t){1.0f, -tc, -sc}; break;
        case 1: d = (vec3_t){-1.0f, -tc, sc}; break;
        case 2: d = (vec3_t){sc, 1.0f, tc}; break;
        case 3: d = (vec3_t){sc, -1.0f, -tc}; break;
        case 4: d = (vec3_t){sc, -tc, 1.0f}; break;
        default: d = (vec3_t){-sc, -tc, -1.0f}; break;
    }
    return sk_v3_norm(d);
}

void sk_environment_dir_cube(vec3_t d, int *face, float *s, float *t)
{
    const float ax = fabsf(d.x), ay = fabsf(d.y), az = fabsf(d.z);
    float ma, sc, tc;
    if (ax >= ay && ax >= az) {
        ma = ax;
        if (d.x > 0.0f) { *face = 0; sc = -d.z; tc = -d.y; } else { *face = 1; sc = d.z; tc = -d.y; }
    } else if (ay >= az) {
        ma = ay;
        if (d.y > 0.0f) { *face = 2; sc = d.x; tc = d.z; } else { *face = 3; sc = d.x; tc = -d.z; }
    } else {
        ma = az;
        if (d.z > 0.0f) { *face = 4; sc = d.x; tc = -d.y; } else { *face = 5; sc = -d.x; tc = -d.y; }
    }
    if (ma <= 0.0f) ma = 1.0f;
    *s = 0.5f * (sc / ma + 1.0f);
    *t = 0.5f * (tc / ma + 1.0f);
}

vec3_t sk_environment_sample_equirect(const sk_env_image_t *image, vec3_t dir)
{
    float u, v;
    sk_environment_dir_equirect(dir, &u, &v);
    float x = u * (float)image->width - 0.5f, y = v * (float)image->height - 0.5f;
    int x0 = (int)floorf(x), y0 = (int)floorf(y);
    const float fx = x - (float)x0, fy = y - (float)y0;
    int x1 = x0 + 1, y1 = y0 + 1;
    vec3_t out = {0, 0, 0};

    /* wrap around the horizon, clamp at the poles */
    x0 = ((x0 % image->width) + image->width) % image->width;
    x1 = ((x1 % image->width) + image->width) % image->width;
    y0 = y0 < 0 ? 0 : (y0 >= image->height ? image->height - 1 : y0);
    y1 = y1 < 0 ? 0 : (y1 >= image->height ? image->height - 1 : y1);
    const int corner_x[4] = {x0, x1, x0, x1}, corner_y[4] = {y0, y0, y1, y1};
    const float weight[4] = {(1 - fx) * (1 - fy), fx * (1 - fy), (1 - fx) * fy, fx * fy};
    for (int i = 0; i < 4; i++) {
        const float *p = &image->rgb[(corner_y[i] * image->width + corner_x[i]) * 3];
        out.x += p[0] * weight[i];
        out.y += p[1] * weight[i];
        out.z += p[2] * weight[i];
    }
    return out;
}

static vec3_t sample_face(const sk_env_cube_t *cube, int mip, int face, float s, float t)
{
    const int size = cube->size >> mip > 0 ? cube->size >> mip : 1;
    float x = s * (float)size - 0.5f, y = t * (float)size - 0.5f;
    int x0 = (int)floorf(x), y0 = (int)floorf(y);
    const float fx = x - (float)x0, fy = y - (float)y0;
    int x1 = x0 + 1, y1 = y0 + 1;
    const float *data = cube->mips[mip] + (size_t)face * (size_t)size * (size_t)size * 3;
    vec3_t out = {0, 0, 0};

    x0 = x0 < 0 ? 0 : (x0 >= size ? size - 1 : x0);
    x1 = x1 < 0 ? 0 : (x1 >= size ? size - 1 : x1);
    y0 = y0 < 0 ? 0 : (y0 >= size ? size - 1 : y0);
    y1 = y1 < 0 ? 0 : (y1 >= size ? size - 1 : y1);
    const int corner_x[4] = {x0, x1, x0, x1}, corner_y[4] = {y0, y0, y1, y1};
    const float weight[4] = {(1 - fx) * (1 - fy), fx * (1 - fy), (1 - fx) * fy, fx * fy};
    for (int i = 0; i < 4; i++) {
        const float *p = &data[(corner_y[i] * size + corner_x[i]) * 3];
        out.x += p[0] * weight[i];
        out.y += p[1] * weight[i];
        out.z += p[2] * weight[i];
    }
    return out;
}

vec3_t sk_environment_sample_cube(const sk_env_cube_t *cube, vec3_t dir, float lod)
{
    int face;
    float s, t;
    const float max_lod = (float)(cube->mip_count - 1);
    lod = lod < 0.0f ? 0.0f : (lod > max_lod ? max_lod : lod);
    const int m0 = (int)floorf(lod);
    const int m1 = m0 + 1 < cube->mip_count ? m0 + 1 : m0;
    const float f = lod - (float)m0;

    sk_environment_dir_cube(dir, &face, &s, &t);
    const vec3_t a = sample_face(cube, m0, face, s, t);
    if (f <= 0.0f || m1 == m0) {
        return a;
    }
    const vec3_t b = sample_face(cube, m1, face, s, t);
    return (vec3_t){a.x + (b.x - a.x) * f, a.y + (b.y - a.y) * f, a.z + (b.z - a.z) * f};
}

static void sh_basis(vec3_t n, float y[9])
{
    y[0] = 0.282095f;
    y[1] = 0.488603f * n.y;
    y[2] = 0.488603f * n.z;
    y[3] = 0.488603f * n.x;
    y[4] = 1.092548f * n.x * n.y;
    y[5] = 1.092548f * n.y * n.z;
    y[6] = 0.315392f * (3.0f * n.z * n.z - 1.0f);
    y[7] = 1.092548f * n.x * n.z;
    y[8] = 0.546274f * (n.x * n.x - n.y * n.y);
}

void sk_environment_project_sh(const sk_env_image_t *image, sk_env_sh_t *out)
{
    /* Lambert convolution per band (Ramamoorthi & Hanrahan), divided by pi */
    static const float band[9] = {1.0f, 2.0f / 3.0f, 2.0f / 3.0f, 2.0f / 3.0f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f};
    double sum[9][3] = {{0}};
    const double pixel_area = (2.0 * M_PI / image->width) * (M_PI / image->height);

    for (int py = 0; py < image->height; py++) {
        const float v = ((float)py + 0.5f) / (float)image->height;
        const double solid_angle = pixel_area * sin(v * M_PI);
        for (int px = 0; px < image->width; px++) {
            const vec3_t dir = sk_environment_equirect_dir(((float)px + 0.5f) / (float)image->width, v);
            const float *rgb = &image->rgb[(py * image->width + px) * 3];
            float y[9];
            sh_basis(dir, y);
            for (int k = 0; k < 9; k++) {
                for (int c = 0; c < 3; c++) {
                    sum[k][c] += rgb[c] * y[k] * solid_angle;
                }
            }
        }
    }
    for (int k = 0; k < 9; k++) {
        for (int c = 0; c < 3; c++) {
            out->c[k][c] = (float)sum[k][c] * band[k];
        }
    }
}

vec3_t sk_environment_eval_sh(const sk_env_sh_t *sh, vec3_t n)
{
    float y[9];
    vec3_t out = {0, 0, 0};
    sh_basis(n, y);
    for (int k = 0; k < 9; k++) {
        out.x += sh->c[k][0] * y[k];
        out.y += sh->c[k][1] * y[k];
        out.z += sh->c[k][2] * y[k];
    }
    return out;
}

void sk_environment_cube_free(sk_env_cube_t *cube)
{
    for (int m = 0; m < 16; m++) {
        free(cube->mips[m]);
        cube->mips[m] = NULL;
    }
    cube->mip_count = 0;
}

static bool cube_alloc(sk_env_cube_t *cube, int size, int mip_count)
{
    memset(cube, 0, sizeof(*cube));
    cube->size = size;
    cube->mip_count = mip_count;
    for (int m = 0; m < mip_count; m++) {
        const size_t s = (size_t)(size >> m > 0 ? size >> m : 1);
        cube->mips[m] = (float *)calloc(6 * s * s * 3, sizeof(float));
        if (cube->mips[m] == NULL) {
            sk_environment_cube_free(cube);
            return false;
        }
    }
    return true;
}

bool sk_environment_cube_from_equirect(const sk_env_image_t *image, int size, sk_env_cube_t *out)
{
    int mip_count = 1;
    while ((size >> (mip_count - 1)) > 1 && mip_count < 16) mip_count++;
    if (!cube_alloc(out, size, mip_count)) {
        return false;
    }
    /* mip 0: 2x2 supersampled per texel */
    for (int face = 0; face < 6; face++) {
        for (int y = 0; y < size; y++) {
            for (int x = 0; x < size; x++) {
                float *p = &out->mips[0][((size_t)face * size * size + (size_t)y * size + x) * 3];
                for (int sy = 0; sy < 2; sy++) {
                    for (int sx = 0; sx < 2; sx++) {
                        const vec3_t d = sk_environment_cube_dir(face, ((float)x + 0.25f + 0.5f * sx) / (float)size,
                                                                 ((float)y + 0.25f + 0.5f * sy) / (float)size);
                        const vec3_t c = sk_environment_sample_equirect(image, d);
                        p[0] += c.x * 0.25f;
                        p[1] += c.y * 0.25f;
                        p[2] += c.z * 0.25f;
                    }
                }
            }
        }
    }
    /* box-filtered mips */
    for (int m = 1; m < mip_count; m++) {
        const int src = size >> (m - 1), dst = size >> m > 0 ? size >> m : 1;
        for (int face = 0; face < 6; face++) {
            for (int y = 0; y < dst; y++) {
                for (int x = 0; x < dst; x++) {
                    float *p = &out->mips[m][((size_t)face * dst * dst + (size_t)y * dst + x) * 3];
                    for (int c = 0; c < 3; c++) {
                        const float *s = out->mips[m - 1] + (size_t)face * src * src * 3;
                        const int x1 = 2 * x + 1 < src ? 2 * x + 1 : 2 * x, y1 = 2 * y + 1 < src ? 2 * y + 1 : 2 * y;
                        p[c] = 0.25f * (s[(2 * y * src + 2 * x) * 3 + c] + s[(2 * y * src + x1) * 3 + c] +
                                        s[(y1 * src + 2 * x) * 3 + c] + s[(y1 * src + x1) * 3 + c]);
                    }
                }
            }
        }
    }
    return true;
}

static float radical_inverse(uint32_t bits)
{
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return (float)bits * 2.3283064365386963e-10f;
}

/* GGX half vector around +z for Hammersley point i of n (alpha = roughness^2). */
static vec3_t importance_ggx(int i, int n, float alpha)
{
    const float xi_x = (float)i / (float)n, xi_y = radical_inverse((uint32_t)i);
    const float phi = 2.0f * PI_F * xi_x;
    const float cos_theta = sqrtf((1.0f - xi_y) / (1.0f + (alpha * alpha - 1.0f) * xi_y));
    const float sin_theta = sqrtf(1.0f - cos_theta * cos_theta);
    return (vec3_t){sin_theta * cosf(phi), sin_theta * sinf(phi), cos_theta};
}

static vec3_t to_basis(vec3_t v, vec3_t n)
{
    const vec3_t up = fabsf(n.z) < 0.999f ? (vec3_t){0, 0, 1} : (vec3_t){1, 0, 0};
    const vec3_t tx = sk_v3_norm(sk_v3_cross(up, n));
    const vec3_t ty = sk_v3_cross(n, tx);
    return (vec3_t){tx.x * v.x + ty.x * v.y + n.x * v.z, tx.y * v.x + ty.y * v.y + n.y * v.z,
                    tx.z * v.x + ty.z * v.y + n.z * v.z};
}

bool sk_environment_prefilter(const sk_env_cube_t *source, int size, int mip_count, int samples, sk_env_cube_t *out)
{
    const float source_texel_solid_angle = 4.0f * PI_F / (6.0f * (float)source->size * (float)source->size);

    if (!cube_alloc(out, size, mip_count)) {
        return false;
    }
    for (int m = 0; m < mip_count; m++) {
        const int s = size >> m > 0 ? size >> m : 1;
        const float roughness = mip_count > 1 ? (float)m / (float)(mip_count - 1) : 0.0f;
        const float alpha = roughness * roughness;
        for (int face = 0; face < 6; face++) {
            for (int y = 0; y < s; y++) {
                for (int x = 0; x < s; x++) {
                    float *p = &out->mips[m][((size_t)face * s * s + (size_t)y * s + x) * 3];
                    const vec3_t n = sk_environment_cube_dir(face, ((float)x + 0.5f) / (float)s,
                                                             ((float)y + 0.5f) / (float)s);
                    if (m == 0) {
                        /* mirror-like: the source at this resolution */
                        const vec3_t c = sk_environment_sample_cube(source, n, log2f((float)source->size / (float)s));
                        p[0] = c.x; p[1] = c.y; p[2] = c.z;
                        continue;
                    }
                    vec3_t sum = {0, 0, 0};
                    float weight = 0.0f;
                    for (int i = 0; i < samples; i++) {
                        const vec3_t h = to_basis(importance_ggx(i, samples, alpha), n);
                        const float n_dot_h = sk_v3_dot(n, h);
                        const vec3_t l = sk_v3_sub(sk_v3_scale(h, 2.0f * n_dot_h), n); /* reflect n about h (v = n) */
                        const float n_dot_l = sk_v3_dot(n, l);
                        if (n_dot_l <= 0.0f) {
                            continue;
                        }
                        /* filtered importance sampling: read a blurrier source mip where
                         * samples are sparse, which removes noise with few samples */
                        const float a2 = alpha * alpha;
                        const float dd = n_dot_h * n_dot_h * (a2 - 1.0f) + 1.0f;
                        const float pdf = a2 / (PI_F * dd * dd) * 0.25f; /* D * n.h / (4 v.h), v.h == n.h */
                        const float sample_solid_angle = 1.0f / ((float)samples * pdf + 1e-6f);
                        const float lod = 0.5f * log2f(sample_solid_angle / source_texel_solid_angle) + 1.0f;
                        const vec3_t c = sk_environment_sample_cube(source, l, lod);
                        sum = (vec3_t){sum.x + c.x * n_dot_l, sum.y + c.y * n_dot_l, sum.z + c.z * n_dot_l};
                        weight += n_dot_l;
                    }
                    if (weight > 0.0f) {
                        p[0] = sum.x / weight; p[1] = sum.y / weight; p[2] = sum.z / weight;
                    }
                }
            }
        }
    }
    return true;
}

void sk_environment_brdf_lut(int size, int samples, float *out)
{
    for (int y = 0; y < size; y++) {
        const float roughness = ((float)y + 0.5f) / (float)size;
        const float alpha = roughness * roughness;
        const float k = alpha * 0.5f; /* Schlick-GGX for image-based lighting */
        for (int x = 0; x < size; x++) {
            const float n_dot_v = ((float)x + 0.5f) / (float)size;
            const vec3_t v = {sqrtf(1.0f - n_dot_v * n_dot_v), 0.0f, n_dot_v};
            float a = 0.0f, b = 0.0f;
            for (int i = 0; i < samples; i++) {
                const vec3_t h = importance_ggx(i, samples, alpha);
                const float v_dot_h = sk_v3_dot(v, h);
                const vec3_t l = sk_v3_sub(sk_v3_scale(h, 2.0f * v_dot_h), v);
                const float n_dot_l = clamp01(l.z), n_dot_h = clamp01(h.z);
                if (n_dot_l <= 0.0f) {
                    continue;
                }
                const float g = (n_dot_v / (n_dot_v * (1.0f - k) + k)) * (n_dot_l / (n_dot_l * (1.0f - k) + k));
                const float g_vis = g * clamp01(v_dot_h) / (n_dot_h * n_dot_v + 1e-6f);
                const float fc = powf(1.0f - clamp01(v_dot_h), 5.0f);
                a += (1.0f - fc) * g_vis;
                b += fc * g_vis;
            }
            out[(y * size + x) * 2] = a / (float)samples;
            out[(y * size + x) * 2 + 1] = b / (float)samples;
        }
    }
}

uint16_t sk_environment_half_from_float(float value)
{
    uint32_t bits;
    memcpy(&bits, &value, sizeof(bits));
    const uint32_t sign = (bits >> 16) & 0x8000u;
    int32_t exponent = (int32_t)((bits >> 23) & 0xFF) - 127 + 15;
    uint32_t mantissa = bits & 0x007FFFFFu;

    if (((bits >> 23) & 0xFF) == 0xFF) { /* inf or nan */
        return (uint16_t)(sign | 0x7C00u | (mantissa ? 0x200u : 0u));
    }
    if (exponent >= 31) { /* too large: clamp to the largest finite half */
        return (uint16_t)(sign | 0x7BFFu);
    }
    if (exponent <= 0) {
        if (exponent < -10) {
            return (uint16_t)sign; /* underflow to zero */
        }
        mantissa |= 0x00800000u;
        const int shift = 14 - exponent;
        return (uint16_t)(sign | ((mantissa + (1u << (shift - 1))) >> shift));
    }
    /* round to nearest; a carry out of the mantissa correctly bumps the exponent */
    const uint32_t half = ((uint32_t)exponent << 10) + ((mantissa + 0x00001000u) >> 13);
    return (uint16_t)(sign | (half >= 0x7C00u ? 0x7BFFu : half));
}

/* ================================================================ GPU ==== */

static sk_environment_t *resolve(sk_handle_t handle)
{
    uint16_t index = 0;
    if (!sk_handle_pool_resolve(&sk_environment_pool, handle, &index)) {
        if (handle != 0) log_warn("Invalid environment handle (%u)", (unsigned int)handle);
        return NULL;
    }
    return &sk_environments[index];
}

/* RGBA16F cubemap image from a float RGB cube. */
static sg_image make_cube_image(const sk_env_cube_t *cube)
{
    sg_image_desc desc = {
        .type = SG_IMAGETYPE_CUBE,
        .width = cube->size,
        .height = cube->size,
        .num_mipmaps = cube->mip_count,
        .pixel_format = SG_PIXELFORMAT_RGBA16F,
        .label = "sk-environment-cube",
    };
    uint16_t *levels[16] = {NULL};
    sg_image image;

    for (int m = 0; m < cube->mip_count; m++) {
        const size_t s = (size_t)(cube->size >> m > 0 ? cube->size >> m : 1);
        const size_t texels = 6 * s * s;
        levels[m] = (uint16_t *)malloc(texels * 4 * sizeof(uint16_t));
        if (levels[m] == NULL) {
            for (int i = 0; i < m; i++) free(levels[i]);
            return (sg_image){0};
        }
        for (size_t i = 0; i < texels; i++) {
            for (int c = 0; c < 3; c++) {
                levels[m][i * 4 + c] = sk_environment_half_from_float(cube->mips[m][i * 3 + c]);
            }
            levels[m][i * 4 + 3] = sk_environment_half_from_float(1.0f);
        }
        desc.data.mip_levels[m] = (sg_range){.ptr = levels[m], .size = texels * 4 * sizeof(uint16_t)};
    }
    image = sg_make_image(&desc);
    for (int m = 0; m < cube->mip_count; m++) free(levels[m]);
    return image;
}

/* Linear RGB float image from a .hdr (linear already) or PNG/JPEG (sRGB). */
static bool load_image(const char *path, sk_env_image_t *out)
{
    FILE *f = path != NULL ? fopen(path, "rb") : NULL;
    unsigned char *bytes;
    long size;
    int w = 0, h = 0, comp = 0;

    memset(out, 0, sizeof(*out));
    if (f == NULL) return false;
    fseek(f, 0, SEEK_END);
    size = ftell(f);
    fseek(f, 0, SEEK_SET);
    bytes = size > 0 ? (unsigned char *)malloc((size_t)size) : NULL;
    if (bytes == NULL || fread(bytes, 1, (size_t)size, f) != (size_t)size) {
        fclose(f);
        free(bytes);
        return false;
    }
    fclose(f);

    out->rgb = (float *)NULL;
    if (stbi_is_hdr_from_memory(bytes, (int)size)) {
        out->rgb = stbi_loadf_from_memory(bytes, (int)size, &w, &h, &comp, 3);
    } else {
        stbi_uc *pixels = stbi_load_from_memory(bytes, (int)size, &w, &h, &comp, 3);
        if (pixels != NULL) {
            out->rgb = (float *)malloc((size_t)w * (size_t)h * 3 * sizeof(float));
            for (size_t i = 0; out->rgb != NULL && i < (size_t)w * (size_t)h * 3; i++) {
                out->rgb[i] = sk_srgb_to_linear((float)pixels[i] / 255.0f);
            }
            stbi_image_free(pixels);
        }
    }
    free(bytes);
    out->width = w;
    out->height = h;
    return out->rgb != NULL && w > 0 && h > 0;
}

static sk_handle_t find_by_path(const char *path)
{
    if (path == NULL || path[0] == '\0') return 0;
    for (uint16_t i = 1; i < sk_environment_pool.capacity; i++) {
        if (sk_environment_pool.occupied[i] && sk_environments[i].has_path &&
            strcmp(sk_environments[i].path, path) == 0) {
            return sk_handle_pool_handle_from_index(&sk_environment_pool, i);
        }
    }
    return 0;
}

/* The CPU half of loading an environment (any thread). */
typedef struct {
    sk_env_sh_t sh;
    sk_env_cube_t source;
    sk_env_cube_t prefiltered;
} sk_env_prepared_t;

static void *prepare_environment(const char *path)
{
    sk_env_image_t image;
    sk_env_prepared_t *prepared;

    if (!load_image(path, &image)) {
        log_error("sk_environment_create: failed to load %s", path != NULL ? path : "(null)");
        free(image.rgb);
        return NULL;
    }
    prepared = (sk_env_prepared_t *)calloc(1, sizeof(sk_env_prepared_t));
    if (prepared == NULL) {
        free(image.rgb);
        return NULL;
    }
    sk_environment_project_sh(&image, &prepared->sh);
    int source_size = MIN_SOURCE_CUBE_SIZE;
    while (source_size * 2 <= image.width / 4 && source_size < MAX_SOURCE_CUBE_SIZE) source_size *= 2;
    const bool built = sk_environment_cube_from_equirect(&image, source_size, &prepared->source);
    free(image.rgb);
    if (!built || !sk_environment_prefilter(&prepared->source, SK_ENVIRONMENT_CUBE_SIZE, SK_ENVIRONMENT_MIP_COUNT,
                                            PREFILTER_SAMPLES, &prepared->prefiltered)) {
        log_error("sk_environment_create: out of memory preparing %s", path);
        sk_environment_cube_free(&prepared->source);
        free(prepared);
        return NULL;
    }
    return prepared;
}

static void discard_environment(void *data)
{
    sk_env_prepared_t *prepared = (sk_env_prepared_t *)data;
    if (prepared == NULL) return;
    sk_environment_cube_free(&prepared->source);
    sk_environment_cube_free(&prepared->prefiltered);
    free(prepared);
}

static sk_loader_step_t finish_environment(void *data, const char *path, sk_handle_t *resource)
{
    const sk_env_prepared_t *prepared = (const sk_env_prepared_t *)data;
    sk_environment_t env = {0};
    uint16_t index = 0;

    *resource = 0;
    if (!sk_env.ready) {
        log_error("sk_environment_create: environments aren't supported by this graphics backend");
        return SK_LOADER_FAILED;
    }
    env.sh = prepared->sh;
    env.background = make_cube_image(&prepared->source);
    env.background_mip_count = prepared->source.mip_count;
    env.background_view = sg_make_view(&(sg_view_desc){.texture.image = env.background});
    env.cube = make_cube_image(&prepared->prefiltered);
    env.cube_view = sg_make_view(&(sg_view_desc){.texture.image = env.cube});
    if (path != NULL) {
        snprintf(env.path, sizeof(env.path), "%s", path);
        env.has_path = path[0] != '\0';
    }
    env.ref_count = 1;

    const sk_handle_t handle = sk_handle_pool_alloc(&sk_environment_pool);
    if (handle == 0) {
        log_error("environment: pool full (%u)", (unsigned)sk_environment_pool.max - 1u);
        sg_destroy_view(env.cube_view);
        sg_destroy_image(env.cube);
        sg_destroy_view(env.background_view);
        sg_destroy_image(env.background);
        return SK_LOADER_FAILED;
    }
    sk_handle_pool_resolve(&sk_environment_pool, handle, &index);
    sk_environments[index] = env;
    *resource = handle;
    return SK_LOADER_DONE;
}

static sk_handle_t find_environment(const char *path)
{
    const sk_handle_t environment = find_by_path(path);
    if (environment != 0) sk_environment_retain(environment);
    return environment;
}

static const sk_loader_t sk_environment_loader = {
    .name = "environment",
    .prepare = prepare_environment,
    .finish = finish_environment,
    .discard = discard_environment,
    .find = find_environment,
    .release = sk_environment_release,
};

SK_KEEP
sk_handle_t sk_environment_create(const char *path)
{
    if (!sk_env.ready) { /* before the CPU work */
        log_error("sk_environment_create: environments aren't supported by this graphics backend");
        return 0;
    }
    return sk_loader_create(&sk_environment_loader, path);
}

void sk_environment_retain(sk_handle_t environment)
{
    sk_environment_t *env_ptr = resolve(environment);
    if (env_ptr != NULL) env_ptr->ref_count++;
}

SK_KEEP
void sk_environment_release(sk_handle_t environment)
{
    sk_environment_t *env_ptr = resolve(environment);
    if (env_ptr == NULL) return;
    if (env_ptr->ref_count > 0) env_ptr->ref_count--;
    if (env_ptr->ref_count == 0) {
        sg_destroy_view(env_ptr->cube_view);
        sg_destroy_image(env_ptr->cube);
        sg_destroy_view(env_ptr->background_view);
        sg_destroy_image(env_ptr->background);
        memset(env_ptr, 0, sizeof(*env_ptr));
        sk_handle_pool_free(&sk_environment_pool, environment);
    }
}

void sk_environment_get_binding(sk_handle_t environment, sk_environment_binding_t *out)
{
    uint16_t index = 0;
    const bool valid = environment != 0 && sk_handle_pool_resolve(&sk_environment_pool, environment, &index);

    *out = (sk_environment_binding_t){
        .cube = valid ? sk_environments[index].cube_view : sk_env.black_cube_view,
        .brdf_lut = sk_env.lut_view,
        .cube_sampler = sk_env.cube_sampler,
        .lut_sampler = sk_env.lut_sampler,
        .max_lod = (float)(SK_ENVIRONMENT_MIP_COUNT - 1),
        .valid = valid,
    };
    if (valid) {
        out->sh = sk_environments[index].sh;
    }
}

/* ---------------------------------------------------------- background ---- */

static void draw_background(int index)
{
    const sk_background_draw_t *bg = &sk_env.backgrounds[index];
    uint16_t env_index = 0;
    bg_params_t params;

    if (!sk_handle_pool_resolve(&sk_environment_pool, bg->environment, &env_index)) {
        return; /* destroyed after it was queued */
    }
    const sk_environment_t *env_ptr = &sk_environments[env_index];
    memcpy(params.inv_view_proj, bg->inv_view_proj.m, sizeof(params.inv_view_proj));
    params.bg_env[0] = bg->intensity;
    params.bg_env[1] = bg->lod * (float)(env_ptr->background_mip_count - 1);
    params.bg_env[2] = cosf(bg->rotation);
    params.bg_env[3] = sinf(bg->rotation);
    params.bg_tonemap[0] = (float)bg->tonemap;
    params.bg_tonemap[1] = powf(2.0f, bg->exposure);
    params.bg_tonemap[2] = 0.0f;
    params.bg_tonemap[3] = 0.0f;
    sg_apply_pipeline(sk_env.background_pipeline);
    sg_apply_bindings(&(sg_bindings){
        .vertex_buffers[0] = sk_env.background_triangle,
        .views[VIEW_bg_tex] = env_ptr->background_view,
        .samplers[SMP_bg_smp] = sk_env.cube_sampler,
    });
    sg_apply_uniforms(UB_bg_params, &SG_RANGE(params));
    sg_draw(0, 3, 1);
}

void sk_environment_submit_background(sk_handle_t environment, float blur, float intensity, float rotation,
                                      int tonemap, float exposure)
{
    sk_camera3d_t cam;
    sk_background_draw_t *bg;

    if (!sk_env.ready || resolve(environment) == NULL || !sk_camera3d_get_active_data(&cam)) {
        return;
    }
    if (sk_env.background_count >= MAX_BACKGROUND_DRAWS) {
        return;
    }
    const vec2_t size = sk_render_target_size();
    const float aspect = size.y > 0.0f ? size.x / size.y : 1.0f;
    const sk_mat4_t view_proj = sk_mat4_mul(sk_camera3d_projection(&cam, aspect), sk_camera3d_view(&cam));
    bg = &sk_env.backgrounds[sk_env.background_count];
    *bg = (sk_background_draw_t){
        .inv_view_proj = sk_mat4_inverse(view_proj),
        .environment = environment,
        .lod = clamp01(blur), /* scaled by the background's mip count when drawn */
        .intensity = intensity,
        .rotation = rotation,
        .tonemap = tonemap,
        .exposure = exposure,
    };
    sk_render_submit_callback(draw_background, sk_env.background_count++);
}

void sk_environment_end_frame(void)
{
    sk_env.background_count = 0;
}

/* ------------------------------------------------------------ lifecycle ---- */

static sg_backend shader_backend(void)
{
    const sg_backend backend = sg_query_backend();
    return backend == SG_BACKEND_DUMMY ? SG_BACKEND_GLCORE : backend; /* see sk_model.c */
}

void sk_environment_init(void)
{
    static const float triangle[] = {-1.0f, -1.0f, 3.0f, -1.0f, -1.0f, 3.0f};
    const int n = SK_ENVIRONMENT_LUT_SIZE;
    uint16_t black[6 * 4] = {0};

    memset(&sk_env, 0, sizeof(sk_env));
    if (!sk_handle_pool_init(&sk_environment_pool, SK_HANDLE_KIND_ENVIRONMENT, "environment",
                             (void **)&sk_environments, sizeof(sk_environment_t), ENVIRONMENTS_INITIAL,
                             SK_HANDLE_POOL_MAX_SLOTS)) {
        log_error("environment: out of memory");
    }

    if (!sg_query_pixelformat(SG_PIXELFORMAT_RGBA16F).filter || !sg_query_pixelformat(SG_PIXELFORMAT_RG16F).filter) {
        log_warn("environment: half-float textures can't be filtered on this backend; environments disabled");
        return;
    }

    /* the split-sum table, baked (tools/gen_brdf_lut.c): computing it here cost tens of
       milliseconds of every startup */
    sk_env.lut = sg_make_image(&(sg_image_desc){
        .width = n, .height = n, .pixel_format = SG_PIXELFORMAT_RG16F,
        .data.mip_levels[0] = SG_RANGE(sk_brdf_lut),
        .label = "sk-brdf-lut",
    });
    sk_env.lut_view = sg_make_view(&(sg_view_desc){.texture.image = sk_env.lut});

    for (int f = 0; f < 6; f++) black[f * 4 + 3] = sk_environment_half_from_float(1.0f);
    sk_env.black_cube = sg_make_image(&(sg_image_desc){
        .type = SG_IMAGETYPE_CUBE, .width = 1, .height = 1, .pixel_format = SG_PIXELFORMAT_RGBA16F,
        .data.mip_levels[0] = {.ptr = black, .size = sizeof(black)},
        .label = "sk-environment-none",
    });
    sk_env.black_cube_view = sg_make_view(&(sg_view_desc){.texture.image = sk_env.black_cube});

    sk_env.cube_sampler = sg_make_sampler(&(sg_sampler_desc){
        .min_filter = SG_FILTER_LINEAR, .mag_filter = SG_FILTER_LINEAR, .mipmap_filter = SG_FILTER_LINEAR,
        .wrap_u = SG_WRAP_CLAMP_TO_EDGE, .wrap_v = SG_WRAP_CLAMP_TO_EDGE, .wrap_w = SG_WRAP_CLAMP_TO_EDGE,
    });
    sk_env.lut_sampler = sg_make_sampler(&(sg_sampler_desc){
        .min_filter = SG_FILTER_LINEAR, .mag_filter = SG_FILTER_LINEAR,
        .wrap_u = SG_WRAP_CLAMP_TO_EDGE, .wrap_v = SG_WRAP_CLAMP_TO_EDGE,
    });

    sk_env.background_shader = sg_make_shader(background_shader_desc(shader_backend()));
    sk_env.background_pipeline = sg_make_pipeline(&(sg_pipeline_desc){
        .shader = sk_env.background_shader,
        .layout.attrs[ATTR_background_bg_position].format = SG_VERTEXFORMAT_FLOAT2,
        .depth = {.compare = SG_COMPAREFUNC_LESS_EQUAL, .write_enabled = false},
        .label = "sk-background-pip",
    });
    sk_env.background_triangle = sg_make_buffer(&(sg_buffer_desc){
        .usage.vertex_buffer = true,
        .data = SG_RANGE(triangle),
        .label = "sk-background-triangle",
    });
    sk_env.ready = true;
    sk_asset_register_loader(".hdr", &sk_environment_loader);
}

void sk_environment_deinit(void)
{
    for (uint16_t i = 1; i < sk_environment_pool.capacity; i++) {
        if (sk_environment_pool.occupied[i]) {
            sg_destroy_view(sk_environments[i].cube_view);
            sg_destroy_image(sk_environments[i].cube);
            sg_destroy_view(sk_environments[i].background_view);
            sg_destroy_image(sk_environments[i].background);
        }
    }
    if (sk_env.ready) {
        sg_destroy_buffer(sk_env.background_triangle);
        sg_destroy_pipeline(sk_env.background_pipeline);
        sg_destroy_shader(sk_env.background_shader);
        sg_destroy_sampler(sk_env.cube_sampler);
        sg_destroy_sampler(sk_env.lut_sampler);
        sg_destroy_view(sk_env.black_cube_view);
        sg_destroy_image(sk_env.black_cube);
        sg_destroy_view(sk_env.lut_view);
        sg_destroy_image(sk_env.lut);
    }
    memset(&sk_env, 0, sizeof(sk_env));
    sk_handle_pool_destroy(&sk_environment_pool);
}
