#include "sk_model.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "internal/exports.h"
#include "internal/sk_asset.h"
#include "internal/sk_camera3d.h"
#include "internal/sk_handle_pool.h"
#include "internal/sk_internal.h"
#include "internal/sk_light.h"
#include "internal/sk_material.h"
#include "internal/sk_math.h"
#include "internal/sk_model.h"
#include "internal/sk_pick.h"
#include "internal/sk_render.h"
#include "internal/sk_scene.h"
#include "internal/sk_texture.h"
#include "sk_material.h"
#include "sk_logger.h"

#include "cgltf.h"
#include "sokol_gfx.h"
#include "stb_image.h"

/* generated by sokol-shdc from src/shaders/sk_model.glsl (`make shaders`) —
 * shader sources + per-backend reflection + the vs_/fs_params_t UB structs */
#include "shaders/sk_model.glsl.h"

#define MAX_MODELS 256
#define MAX_MESHES 256
#define MAX_MODEL_DRAWS 1024 /* model placements queued per frame */
#define MAX_MODEL_ITEMS 8192 /* primitives queued per frame */
#define SK_MAX_JOINTS 128
#define MAX_BLEND_PRIMS 1024 /* transparent primitives sorted per immediate draw */
#define SK_MAX_MATERIAL_SLOTS 32 /* material slots a model can override */

/* ----------------------------------------------------------- data types ---- */

typedef struct {
    sg_buffer vbuf;
    sg_buffer ibuf;
    int index_count;
    int material;       /* slot in the mesh's materials (and a model's overrides) */
    bool skinned;
    vec3_t pmin, pmax; /* local-space AABB (for picking) */
    /* CPU-side bind-pose geometry retained for narrow-phase triangle picking */
    float *pick_positions; /* 3 floats per vertex, mesh-local space (bind pose) */
    uint32_t *pick_indices;
    int pick_vertex_count;
    /* skinned primitives: joints and weights, to pose pick geometry like the shader */
    uint8_t *pick_joints;  /* 4 per vertex */
    float *pick_weights;   /* 4 per vertex */
    /* for alpha-tested picking of MASK / BLEND materials */
    float *pick_uvs[2];    /* texture coordinate sets 0 and 1, 2 per vertex; NULL = absent */
    float *pick_alpha;     /* vertex color alpha, 1 per vertex; NULL = absent or all opaque */
} sk_primitive_t;

/* node transform (base from glTF + per-frame working copy) */
typedef struct {
    vec3_t t; quat_t r; vec3_t s;
    int parent;
} sk_node_t;

typedef struct {
    int node;        /* target node index */
    int path;        /* 0=T, 1=R, 2=S */
    int interp;      /* 0=linear, 1=step */
    float *times;
    float *values;   /* 3 per key (T/S) or 4 (R) */
    int key_count;
} sk_anim_channel_t;

typedef struct {
    sk_anim_channel_t *channels;
    int channel_count;
    float duration;
} sk_animation_t;

/* Mesh resource: shared, refcounted, deduped data built from a source asset (a
 * glTF/glb path) or generated. Holds CPU geometry (primitives incl. retained
 * pick data), GPU buffers, skeleton, and animation clips. Many Model objects may
 * reference one Mesh. */
typedef struct {
    sk_primitive_t *prims;
    int prim_count;

    /* skeleton */
    sk_node_t *nodes;
    int node_count;
    int *joint_nodes;
    sk_mat4_t *inverse_bind;
    int joint_count;
    bool has_skin;

    /* animation clips (shared; playback state lives on the model) */
    sk_animation_t *animations;
    int animation_count;

    /* materials, one per glTF material (plus glTF's default material when a
     * primitive has none); each referenced by the mesh */
    sk_handle_t *materials;
    int material_count;

    /* merged local-space AABB (for broadphase/picking) */
    vec3_t lmin, lmax;

    int ref_count;
    char path[256];
    bool has_path;
} sk_mesh_t;

/* Model object: lightweight per-placement runtime state. References a Mesh
 * resource and owns its own transform, tint, visibility, and animation
 * playback. */
typedef struct {
    sk_handle_t mesh;

    vec3_t position;
    vec3_t rotation;
    vec3_t scale;
    sk_handle_t tint;
    bool visible;
    sk_handle_t materials[SK_MAX_MATERIAL_SLOTS]; /* per-slot overrides (referenced); 0 = mesh's */

    /* animation playback */
    int cur_anim;
    float anim_time;
    float anim_speed;
    bool anim_loop;
    sk_mat4_t joint_matrices[SK_MAX_JOINTS];
    unsigned pose_version; /* bumped when joint_matrices change; 0 = bind pose */

    /* posed pick geometry, built on demand when a pick needs it */
    float *posed_positions;  /* skinned primitives' vertices in the current pose */
    int posed_capacity;      /* vertices allocated */
    unsigned posed_version;  /* pose_version the cache was built for (0 = none) */
    sk_handle_t posed_mesh;  /* mesh the cache was built for */
    vec3_t posed_min, posed_max;
} sk_model_t;

/* One model placement queued this frame (matrices and tint captured at submit). */
typedef struct {
    sk_handle_t model;
    int pass;             /* render pass it was queued in (sk_render_current_pass) */
    sk_mat4_t mvp;
    sk_mat4_t model_mat;
    sk_mat4_t model_view; /* for view-space depth when sorting transparent parts */
    sk_mat4_t normal_mat; /* inverse transpose of model_mat */
    vec3_t camera_pos;
    color_t tint;
    int light_env;        /* lighting environment index, -1 = unlit */
    int light_count;      /* lights selected for this placement */
    int lights[SK_MAX_DRAW_LIGHTS]; /* indices into the environment's lights */
} sk_model_draw_t;

/* One primitive to draw, in submission order. sk_render replays ranges of these. */
typedef struct {
    int draw;     /* index into sk_model_draws */
    int prim;     /* index into the mesh's primitives */
    bool blended; /* use the blended pipeline */
} sk_model_item_t;

/* A transparent primitive of an immediate sk_model_draw(), sorted within that draw. */
typedef struct {
    int prim;
    float depth;
} sk_blend_prim_t;

/* vs_params_t / vs_skin_params_t / fs_params_t are generated into
 * shaders/sk_model.glsl.h (included above) and mirror the shader uniform blocks. */

static sk_mesh_t sk_meshes[MAX_MESHES];
static sk_handle_pool_t sk_mesh_pool;
static uint16_t sk_mesh_free_indices[MAX_MESHES];
static uint16_t sk_mesh_generations[MAX_MESHES];
static unsigned char sk_mesh_occupied[MAX_MESHES];

static sk_model_t sk_models[MAX_MODELS];
static sk_handle_pool_t sk_model_pool;
static uint16_t sk_model_free_indices[MAX_MODELS];
static uint16_t sk_model_generations[MAX_MODELS];
static unsigned char sk_model_occupied[MAX_MODELS];

/* [skinned][blended][double_sided] */
static sg_pipeline sk_pips[2][2][2];
static sg_shader sk_shd_static;
static sg_shader sk_shd_skinned;
/* material texture samplers, made on first use: [wrap_u][wrap_v][filter][mipmaps] */
static sg_sampler sk_model_samplers[3][3][2][2];
static sg_image sk_model_white_img;
static sg_view sk_model_white_view;
static sg_image sk_model_flat_normal_img;
static sg_view sk_model_flat_normal_view;

static sk_model_draw_t sk_model_draws[MAX_MODEL_DRAWS];
static int sk_model_draw_count;
static sk_model_item_t sk_model_items[MAX_MODEL_ITEMS];
static int sk_model_item_count;
static sk_blend_prim_t sk_blend_prims[MAX_BLEND_PRIMS];
static bool sk_model_queue_full_logged;

static void draw_immediate(sk_handle_t handle);
static void draw_opaque(sk_handle_t handle);
static int collect_transparent(sk_handle_t handle, const sk_camera3d_t *cam,
                               sk_transparent_item_t *out, int max_items);
static void draw_transparent(sk_handle_t handle, int part);
static bool model_bounds(sk_handle_t handle, vec3_t *lmin, vec3_t *lmax, sk_mat4_t *model_mat);
static bool model_pick(sk_handle_t handle, vec3_t origin, vec3_t dir, sk_pick_result_t *out);
static sk_model_t *resolve(sk_handle_t handle);
static sk_mesh_t *resolve_mesh(sk_handle_t handle);
static void release_mesh(sk_handle_t mesh_handle);
static void free_mesh_cpu(sk_mesh_t *mesh);
static unsigned char *read_file_bytes(const char *path, int *out_size);

/* ------------------------------------------------------------- shaders ----- */

/* Shader sources + per-backend reflection (GL core / WebGL2 / WebGPU) are
 * generated by sokol-shdc into shaders/sk_model.glsl.h; the right variant is
 * selected at runtime via sg_query_backend(). Edit src/shaders/sk_model.glsl
 * and regenerate with `make shaders`. */

/* sokol-shdc generates shader descriptions for real backends only. The dummy
 * backend (headless builds) never compiles source but still validates the layout
 * (attributes, uniform blocks, textures), so give it the GL description. */
static sg_backend shader_backend(void)
{
    const sg_backend backend = sg_query_backend();
    return backend == SG_BACKEND_DUMMY ? SG_BACKEND_GLCORE : backend;
}

static sg_shader make_static_shader(void)
{
    return sg_make_shader(model_static_shader_desc(shader_backend()));
}

static sg_shader make_skinned_shader(void)
{
    return sg_make_shader(model_skinned_shader_desc(shader_backend()));
}

/* ----------------------------------------------------------- gltf load ----- */

/* Textures created while loading one glTF file, one per glTF image (0 = not
 * created yet). The loader holds one reference to each; materials add their own. */
typedef struct {
    sk_handle_t texture; /* 0 = not loaded yet */
    bool failed;         /* couldn't be read or decoded (warned once) */
} sk_gltf_image_t;

typedef struct {
    const cgltf_data *gltf;
    const char *path; /* the glTF file, for images in files next to it */
    sk_gltf_image_t *images;
    bool texcoord_warned;
} sk_gltf_textures_t;

/* The encoded bytes of a glTF image: from a buffer view, a data: URI, or a file
 * relative to the glTF file. `*owned` is set when the caller must free them. */
static const unsigned char *image_bytes(const sk_gltf_textures_t *cache, const cgltf_image *img, int *size,
                                        void **owned)
{
    const cgltf_buffer_view *bv = img->buffer_view;
    const char *base64;
    char path[512];

    *owned = NULL;
    if (bv != NULL) {
        if (bv->buffer == NULL || bv->buffer->data == NULL) return NULL;
        *size = (int)bv->size;
        return (const unsigned char *)bv->buffer->data + bv->offset;
    }
    if (img->uri == NULL) return NULL;
    if (strncmp(img->uri, "data:", 5) == 0) {
        size_t len, padding = 0;
        cgltf_options options = {0};
        base64 = strstr(img->uri, ";base64,");
        if (base64 == NULL) return NULL;
        base64 += 8;
        len = strlen(base64);
        while (len > 0 && base64[len - 1] == '=') len--, padding++;
        *size = (int)((len + padding) / 4 * 3 - padding);
        if (cgltf_load_buffer_base64(&options, (cgltf_size)*size, base64, owned) != cgltf_result_success) return NULL;
        return (const unsigned char *)*owned;
    }
    if (!sk_asset_is_relative_uri(img->uri) || cache->path == NULL ||
        !sk_asset_join_relative(cache->path, img->uri, path, sizeof(path))) {
        return NULL;
    }
    *owned = read_file_bytes(path, size);
    return (const unsigned char *)*owned;
}

/* Decode a glTF image into a texture (cached per image). 0 when it can't be
 * loaded (warned once per image). */
static sk_handle_t load_image(sk_gltf_textures_t *cache, const cgltf_image *img)
{
    const unsigned char *bytes;
    void *owned = NULL;
    int w = 0, h = 0, comp = 0, size = 0;
    stbi_uc *pixels;
    size_t index;

    if (img == NULL) {
        return 0;
    }
    index = (size_t)(img - cache->gltf->images);
    if (cache->images[index].texture != 0 || cache->images[index].failed) {
        return cache->images[index].texture;
    }
    cache->images[index].failed = true; /* until it loads */
    bytes = image_bytes(cache, img, &size, &owned);
    if (bytes == NULL) {
        log_warn("model: %s: image %zu (%s) couldn't be read; using the placeholder texture", cache->path,
                 index, img->uri != NULL && strncmp(img->uri, "data:", 5) != 0 ? img->uri : "embedded");
        return 0;
    }
    pixels = stbi_load_from_memory(bytes, size, &w, &h, &comp, 4);
    free(owned);
    if (pixels == NULL) {
        log_warn("model: %s: image %zu couldn't be decoded (%s); using the placeholder texture", cache->path, index,
                 stbi_failure_reason());
        return 0;
    }
    cache->images[index].texture = sk_texture_create_rgba(pixels, w, h);
    cache->images[index].failed = cache->images[index].texture == 0;
    stbi_image_free(pixels);
    return cache->images[index].texture;
}

static sk_texture_wrap_t gltf_wrap(cgltf_wrap_mode mode)
{
    switch (mode) {
        case cgltf_wrap_mode_clamp_to_edge: return SK_TEXTURE_WRAP_CLAMP;
        case cgltf_wrap_mode_mirrored_repeat: return SK_TEXTURE_WRAP_MIRROR;
        default: return SK_TEXTURE_WRAP_REPEAT;
    }
}

/* Assign a glTF texture to material parameter `name`, with its texture coordinate
 * set, KHR_texture_transform and sampler. */
static void set_texture(sk_gltf_textures_t *cache, sk_handle_t material, const char *name,
                        const cgltf_texture_view *view)
{
    const cgltf_sampler *sampler;
    sk_handle_t texture;
    char param[64];
    int texcoord;

    if (view->texture == NULL) {
        return;
    }
    if (view->texture->image == NULL) {
        log_warn("model: %s: a texture has no image in a supported format (PNG, JPEG); using the placeholder texture",
                 cache->path);
    }
    texture = load_image(cache, view->texture->image);
    if (texture == 0) {
        /* Color textures show the placeholder so the problem is visible. Data
         * textures (normal, metallic-roughness, occlusion) stay empty: a checker
         * there would only distort the lighting. */
        if (strcmp(name, "base_color_texture") != 0 && strcmp(name, "emissive_texture") != 0) {
            return;
        }
        texture = sk_texture_get_placeholder();
    }
    sk_material_set_texture(material, name, texture);

    texcoord = view->has_transform && view->transform.has_texcoord ? view->transform.texcoord : view->texcoord;
    snprintf(param, sizeof(param), "%s_texcoord", name);
    if (texcoord > 1) {
        if (!cache->texcoord_warned) {
            log_warn("model: texture coordinate set %d isn't supported (0 and 1 are); set 0 is used", texcoord);
            cache->texcoord_warned = true;
        }
        texcoord = 0;
    }
    sk_material_set_int(material, param, texcoord);

    if (view->has_transform) {
        snprintf(param, sizeof(param), "%s_offset", name);
        sk_material_set_vec2(material, param, view->transform.offset[0], view->transform.offset[1]);
        snprintf(param, sizeof(param), "%s_rotation", name);
        sk_material_set_float(material, param, view->transform.rotation);
        snprintf(param, sizeof(param), "%s_scale", name);
        sk_material_set_vec2(material, param, view->transform.scale[0], view->transform.scale[1]);
    }

    sampler = view->texture->sampler;
    if (sampler != NULL) {
        const cgltf_filter_type min = sampler->min_filter, mag = sampler->mag_filter;
        const bool nearest_min = min == cgltf_filter_type_nearest || min == cgltf_filter_type_nearest_mipmap_nearest ||
                                 min == cgltf_filter_type_nearest_mipmap_linear;
        /* one filter for both: magnification decides when given (it's what shows up close) */
        const bool nearest = mag == cgltf_filter_type_nearest || (mag == cgltf_filter_type_undefined && nearest_min);
        sk_material_set_texture_sampling(material, name, gltf_wrap(sampler->wrap_s), gltf_wrap(sampler->wrap_t),
                                         nearest ? SK_TEXTURE_FILTER_NEAREST : SK_TEXTURE_FILTER_LINEAR);
        sk_material_set_texture_mipmaps(material, name,
                                        min != cgltf_filter_type_nearest && min != cgltf_filter_type_linear);
    }
}

/* Create a material from a glTF material; NULL gives glTF's default material. */
static sk_handle_t create_gltf_material(sk_gltf_textures_t *cache, const cgltf_material *src)
{
    sk_handle_t material = sk_material_create(src != NULL && src->unlit ? SK_MATERIAL_UNLIT : SK_MATERIAL_PBR);
    const cgltf_pbr_metallic_roughness *pbr;
    float strength;

    if (material == 0 || src == NULL) {
        return material;
    }
    switch (src->alpha_mode) {
        case cgltf_alpha_mode_mask: sk_material_set_alpha_mode(material, SK_MATERIAL_ALPHA_MASK, src->alpha_cutoff); break;
        case cgltf_alpha_mode_blend: sk_material_set_alpha_mode(material, SK_MATERIAL_ALPHA_BLEND, src->alpha_cutoff); break;
        default: break;
    }
    sk_material_set_double_sided(material, src->double_sided);
    if (src->has_pbr_metallic_roughness) {
        pbr = &src->pbr_metallic_roughness;
        sk_material_set_vec4(material, "base_color", pbr->base_color_factor[0], pbr->base_color_factor[1],
                             pbr->base_color_factor[2], pbr->base_color_factor[3]);
        sk_material_set_float(material, "metallic", pbr->metallic_factor);
        sk_material_set_float(material, "roughness", pbr->roughness_factor);
        set_texture(cache, material, "base_color_texture", &pbr->base_color_texture);
        set_texture(cache, material, "metallic_roughness_texture", &pbr->metallic_roughness_texture);
    }
    if (src->normal_texture.texture != NULL) {
        set_texture(cache, material, "normal_texture", &src->normal_texture);
        sk_material_set_float(material, "normal_scale", src->normal_texture.scale);
    }
    if (src->occlusion_texture.texture != NULL) {
        set_texture(cache, material, "occlusion_texture", &src->occlusion_texture);
        sk_material_set_float(material, "occlusion_strength", src->occlusion_texture.scale);
    }
    strength = src->has_emissive_strength ? src->emissive_strength.emissive_strength : 1.0f;
    sk_material_set_vec3(material, "emissive", src->emissive_factor[0] * strength,
                         src->emissive_factor[1] * strength, src->emissive_factor[2] * strength);
    set_texture(cache, material, "emissive_texture", &src->emissive_texture);
    return material;
}

/* Tangents for normal mapping from triangle positions and texture coordinates
 * (per-vertex average, orthogonalized against the normal), in glTF's convention:
 * the tangent follows increasing u, and w is the bitangent sign, with bitangent =
 * cross(normal, tangent.xyz) * w pointing toward decreasing v (texture up). Vertices without a usable
 * texture mapping get any tangent perpendicular to their normal. */
void sk_model_generate_tangents(const float *positions, const float *normals, const float *uvs, int vertex_count,
                                const uint32_t *indices, int index_count, float *tangents)
{
    float *bitangents = (float *)calloc((size_t)vertex_count * 3, sizeof(float));

    memset(tangents, 0, (size_t)vertex_count * 4 * sizeof(float));
    for (int k = 0; bitangents != NULL && k + 2 < index_count; k += 3) {
        const uint32_t i0 = indices[k], i1 = indices[k + 1], i2 = indices[k + 2];
        float e1[3], e2[3], sdir[3], tdir[3], du1, dv1, du2, dv2, det;
        if ((int)i0 >= vertex_count || (int)i1 >= vertex_count || (int)i2 >= vertex_count) {
            continue;
        }
        for (int c = 0; c < 3; c++) {
            e1[c] = positions[i1 * 3 + c] - positions[i0 * 3 + c];
            e2[c] = positions[i2 * 3 + c] - positions[i0 * 3 + c];
        }
        du1 = uvs[i1 * 2] - uvs[i0 * 2];
        dv1 = uvs[i1 * 2 + 1] - uvs[i0 * 2 + 1];
        du2 = uvs[i2 * 2] - uvs[i0 * 2];
        dv2 = uvs[i2 * 2 + 1] - uvs[i0 * 2 + 1];
        det = du1 * dv2 - du2 * dv1;
        if (det > -1e-12f && det < 1e-12f) {
            continue;
        }
        det = 1.0f / det;
        for (int c = 0; c < 3; c++) {
            sdir[c] = (e1[c] * dv2 - e2[c] * dv1) * det;
            tdir[c] = (e2[c] * du1 - e1[c] * du2) * det;
        }
        for (int v = 0; v < 3; v++) {
            const uint32_t i = indices[k + v];
            for (int c = 0; c < 3; c++) {
                tangents[i * 4 + c] += sdir[c];
                bitangents[i * 3 + c] += tdir[c];
            }
        }
    }
    for (int i = 0; i < vertex_count; i++) {
        const vec3_t n = {normals[i * 3], normals[i * 3 + 1], normals[i * 3 + 2]};
        vec3_t t = {tangents[i * 4], tangents[i * 4 + 1], tangents[i * 4 + 2]};
        const vec3_t b = bitangents != NULL ? (vec3_t){bitangents[i * 3], bitangents[i * 3 + 1], bitangents[i * 3 + 2]}
                                            : (vec3_t){0, 0, 0};
        float w = 1.0f;
        t = sk_v3_sub(t, sk_v3_scale(n, sk_v3_dot(n, t)));
        if (sk_v3_dot(t, t) < 1e-12f) {
            /* no texture mapping here: any direction perpendicular to the normal */
            t = fabsf(n.x) < 0.9f ? (vec3_t){1, 0, 0} : (vec3_t){0, 1, 0};
            t = sk_v3_sub(t, sk_v3_scale(n, sk_v3_dot(n, t)));
        } else if (sk_v3_dot(sk_v3_cross(n, t), b) > 0.0f) {
            w = -1.0f; /* the normal map's up (green) points toward decreasing v: bitangent = -dP/dv */
        }
        t = sk_v3_norm(t);
        tangents[i * 4] = t.x;
        tangents[i * 4 + 1] = t.y;
        tangents[i * 4 + 2] = t.z;
        tangents[i * 4 + 3] = w;
    }
    free(bitangents);
}

/* Build a GPU primitive. For static primitives `node_world` (when non-NULL) is
 * baked into positions, normals and tangents: glTF places them with their node's
 * world transform. Skinned primitives ignore it; their joints place them. */
static bool build_primitive(const cgltf_data *g, const cgltf_primitive *prim, bool skinned,
                            const sk_mat4_t *node_world, int default_material, sk_primitive_t *out)
{
    const cgltf_accessor *pos = NULL, *nrm = NULL, *uv[2] = {NULL, NULL}, *tan = NULL, *col = NULL, *jnt = NULL,
                         *wgt = NULL;
    cgltf_size vcount, icount, i;
    float *verts = NULL, *positions = NULL, *normals = NULL, *uvs[2] = {NULL, NULL}, *tangents = NULL,
          *colors = NULL;
    bool translucent = false;
    uint32_t *indices = NULL;
    size_t stride;
    bool ok = false;

    for (cgltf_size a = 0; a < prim->attributes_count; a++) {
        const cgltf_attribute *attr = &prim->attributes[a];
        switch (attr->type) {
            case cgltf_attribute_type_position: pos = attr->data; break;
            case cgltf_attribute_type_normal: nrm = attr->data; break;
            case cgltf_attribute_type_tangent: tan = attr->data; break;
            case cgltf_attribute_type_texcoord: if (attr->index < 2) uv[attr->index] = attr->data; break;
            case cgltf_attribute_type_color: if (attr->index == 0) col = attr->data; break;
            case cgltf_attribute_type_joints: if (attr->index == 0) jnt = attr->data; break;
            case cgltf_attribute_type_weights: if (attr->index == 0) wgt = attr->data; break;
            default: break;
        }
    }
    if (pos == NULL) return false;
    if (skinned && (jnt == NULL || wgt == NULL)) skinned = false;
    if (skinned) node_world = NULL; /* joints place skinned vertices */
    /* position 3, normal 3, texcoord0 2, texcoord1 2, tangent 4, color 4 [, joints 4, weights 4] */
    stride = skinned ? 26 : 18;

    vcount = pos->count;
    memset(out, 0, sizeof(*out));
    positions = (float *)calloc(vcount * 3, sizeof(float));
    normals = (float *)calloc(vcount * 3, sizeof(float));
    uvs[0] = (float *)calloc(vcount * 2, sizeof(float));
    uvs[1] = (float *)calloc(vcount * 2, sizeof(float));
    colors = (float *)malloc(vcount * 4 * sizeof(float));
    tangents = (float *)calloc(vcount * 4, sizeof(float));
    verts = (float *)calloc(vcount * stride, sizeof(float));
    icount = prim->indices != NULL ? prim->indices->count : vcount;
    indices = (uint32_t *)calloc(icount, sizeof(uint32_t));
    if (skinned) {
        out->pick_joints = (uint8_t *)calloc(vcount * 4, 1);
        out->pick_weights = (float *)calloc(vcount * 4, sizeof(float));
    }
    if (positions == NULL || normals == NULL || uvs[0] == NULL || uvs[1] == NULL || colors == NULL ||
        tangents == NULL || verts == NULL || indices == NULL ||
        (skinned && (out->pick_joints == NULL || out->pick_weights == NULL))) {
        goto done;
    }

    /* normals transform by the inverse transpose of the node matrix */
    sk_mat4_t normal_mat = node_world ? sk_mat4_inverse(*node_world) : sk_mat4_identity();
    bool mirrored = false;
    if (node_world) {
        const float *m = node_world->m;
        float det = m[0] * (m[5] * m[10] - m[9] * m[6]) - m[4] * (m[1] * m[10] - m[9] * m[2]) +
                    m[8] * (m[1] * m[6] - m[5] * m[2]);
        mirrored = det < 0.0f; /* keep front faces CCW and tangent frames right-handed */
    }

    out->pmin = (vec3_t){1e30f, 1e30f, 1e30f};
    out->pmax = (vec3_t){-1e30f, -1e30f, -1e30f};
    for (i = 0; i < vcount; i++) {
        float p[3] = {0}, n[3] = {0, 1, 0};
        cgltf_accessor_read_float(pos, i, p, 3);
        if (node_world) {
            vec3_t wp = sk_mat4_mul_point(*node_world, (vec3_t){p[0], p[1], p[2]});
            p[0] = wp.x; p[1] = wp.y; p[2] = wp.z;
        }
        memcpy(&positions[i * 3], p, sizeof(p));
        if (p[0] < out->pmin.x) out->pmin.x = p[0];
        if (p[1] < out->pmin.y) out->pmin.y = p[1];
        if (p[2] < out->pmin.z) out->pmin.z = p[2];
        if (p[0] > out->pmax.x) out->pmax.x = p[0];
        if (p[1] > out->pmax.y) out->pmax.y = p[1];
        if (p[2] > out->pmax.z) out->pmax.z = p[2];
        if (nrm) cgltf_accessor_read_float(nrm, i, n, 3);
        if (node_world) {
            /* transpose(inverse) applied as rows of the inverse */
            const float *im = normal_mat.m;
            vec3_t wn = sk_v3_norm((vec3_t){im[0] * n[0] + im[1] * n[1] + im[2] * n[2],
                                            im[4] * n[0] + im[5] * n[1] + im[6] * n[2],
                                            im[8] * n[0] + im[9] * n[1] + im[10] * n[2]});
            n[0] = wn.x; n[1] = wn.y; n[2] = wn.z;
        }
        memcpy(&normals[i * 3], n, sizeof(n));
        for (int set = 0; set < 2; set++) {
            if (uv[set]) cgltf_accessor_read_float(uv[set], i, &uvs[set][i * 2], 2);
        }
        {
            /* linear rgba; normalized integer colors are read as 0..1 */
            float c[4] = {1, 1, 1, 1};
            if (col) cgltf_accessor_read_float(col, i, c, col->type == cgltf_type_vec4 ? 4 : 3);
            memcpy(&colors[i * 4], c, sizeof(c));
            translucent = translucent || c[3] < 1.0f;
        }
        if (skinned) {
            float j[4] = {0}, w[4] = {0};
            cgltf_accessor_read_float(jnt, i, j, 4);
            cgltf_accessor_read_float(wgt, i, w, 4);
            memcpy(&verts[i * stride + 18], j, sizeof(j));
            memcpy(&verts[i * stride + 22], w, sizeof(w));
            for (int k = 0; k < 4; k++) {
                out->pick_joints[i * 4 + k] = (uint8_t)(j[k] < 255.0f ? j[k] : 255.0f);
                out->pick_weights[i * 4 + k] = w[k];
            }
        }
    }

    for (i = 0; i < icount; i++) {
        indices[i] = prim->indices != NULL ? (uint32_t)cgltf_accessor_read_index(prim->indices, i) : (uint32_t)i;
    }
    if (mirrored) {
        for (i = 0; i + 2 < icount; i += 3) {
            uint32_t tmp = indices[i + 1];
            indices[i + 1] = indices[i + 2];
            indices[i + 2] = tmp;
        }
    }

    if (tan != NULL) {
        for (i = 0; i < vcount; i++) {
            float t[4] = {1, 0, 0, 1};
            cgltf_accessor_read_float(tan, i, t, 4);
            if (node_world) {
                vec3_t wt = sk_v3_norm(sk_mat4_mul_dir(*node_world, (vec3_t){t[0], t[1], t[2]}));
                t[0] = wt.x; t[1] = wt.y; t[2] = wt.z;
                if (mirrored) t[3] = -t[3];
            }
            memcpy(&tangents[i * 4], t, sizeof(t));
        }
    } else {
        /* after baking and winding fixes, so the generated frame matches what's drawn.
         * From texture coordinate set 0: normal maps using set 1 need tangents in the file. */
        sk_model_generate_tangents(positions, normals, uvs[0], (int)vcount, indices, (int)icount, tangents);
    }

    for (i = 0; i < vcount; i++) {
        float *v = &verts[i * stride];
        memcpy(v, &positions[i * 3], 3 * sizeof(float));
        memcpy(v + 3, &normals[i * 3], 3 * sizeof(float));
        memcpy(v + 6, &uvs[0][i * 2], 2 * sizeof(float));
        memcpy(v + 8, &uvs[1][i * 2], 2 * sizeof(float));
        memcpy(v + 10, &tangents[i * 4], 4 * sizeof(float));
        memcpy(v + 14, &colors[i * 4], 4 * sizeof(float));
    }

    out->vbuf = sg_make_buffer(&(sg_buffer_desc){
        .usage.vertex_buffer = true,
        .data = {.ptr = verts, .size = vcount * stride * sizeof(float)}});
    out->ibuf = sg_make_buffer(&(sg_buffer_desc){
        .usage.index_buffer = true,
        .data = {.ptr = indices, .size = icount * sizeof(uint32_t)}});
    out->index_count = (int)icount;
    out->skinned = skinned;
    out->material = prim->material != NULL ? (int)(prim->material - g->materials) : default_material;
    /* retained for picking */
    out->pick_positions = positions;
    out->pick_indices = indices;
    out->pick_vertex_count = (int)vcount;
    for (int set = 0; set < 2; set++) {
        if (uv[set] != NULL) {
            out->pick_uvs[set] = uvs[set];
            uvs[set] = NULL;
        }
    }
    if (translucent) {
        out->pick_alpha = (float *)malloc(vcount * sizeof(float));
        for (i = 0; out->pick_alpha != NULL && i < vcount; i++) out->pick_alpha[i] = colors[i * 4 + 3];
    }
    positions = NULL;
    indices = NULL;
    ok = true;

done:
    if (!ok) {
        free(out->pick_joints);
        free(out->pick_weights);
        memset(out, 0, sizeof(*out));
    }
    free(positions);
    free(normals);
    free(uvs[0]);
    free(uvs[1]);
    free(colors);
    free(tangents);
    free(verts);
    free(indices);
    return ok;
}

static int node_index(const cgltf_data *g, const cgltf_node *n)
{
    return n != NULL ? (int)(n - g->nodes) : -1;
}

static void node_local_trs(const cgltf_node *n, vec3_t *t, quat_t *r, vec3_t *s)
{
    *t = (vec3_t){0, 0, 0};
    *r = (quat_t){0, 0, 0, 1};
    *s = (vec3_t){1, 1, 1};
    if (n->has_matrix) {
        /* decompose column-major matrix into TRS */
        const float *m = n->matrix;
        float sx = sqrtf(m[0]*m[0]+m[1]*m[1]+m[2]*m[2]);
        float sy = sqrtf(m[4]*m[4]+m[5]*m[5]+m[6]*m[6]);
        float sz = sqrtf(m[8]*m[8]+m[9]*m[9]+m[10]*m[10]);
        float r00, r11, r22, tr;
        *t = (vec3_t){m[12], m[13], m[14]};
        *s = (vec3_t){sx, sy, sz};
        if (sx > 1e-6f && sy > 1e-6f && sz > 1e-6f) {
            r00 = m[0]/sx; r11 = m[5]/sy; r22 = m[10]/sz;
            tr = r00 + r11 + r22;
            if (tr > 0.0f) {
                float qs = sqrtf(tr + 1.0f) * 2.0f;
                r->w = 0.25f * qs;
                r->x = (m[6]/sy - m[9]/sz) / qs;
                r->y = (m[8]/sz - m[2]/sx) / qs;
                r->z = (m[1]/sx - m[4]/sy) / qs;
            } else {
                r->w = 1.0f; r->x = r->y = r->z = 0.0f;
            }
        }
        return;
    }
    if (n->has_translation) *t = (vec3_t){n->translation[0], n->translation[1], n->translation[2]};
    if (n->has_rotation) *r = (quat_t){n->rotation[0], n->rotation[1], n->rotation[2], n->rotation[3]};
    if (n->has_scale) *s = (vec3_t){n->scale[0], n->scale[1], n->scale[2]};
}

static void parse_skeleton(sk_mesh_t *mesh, const cgltf_data *g)
{
    const cgltf_skin *skin = NULL;

    /* nodes */
    mesh->node_count = (int)g->nodes_count;
    mesh->nodes = (sk_node_t *)calloc((size_t)mesh->node_count, sizeof(sk_node_t));
    for (int i = 0; i < mesh->node_count; i++) {
        const cgltf_node *n = &g->nodes[i];
        node_local_trs(n, &mesh->nodes[i].t, &mesh->nodes[i].r, &mesh->nodes[i].s);
        mesh->nodes[i].parent = node_index(g, n->parent);
    }

    /* first skin */
    for (cgltf_size i = 0; i < g->nodes_count && skin == NULL; i++) {
        if (g->nodes[i].skin) skin = g->nodes[i].skin;
    }
    if (skin == NULL) return;

    mesh->joint_count = (int)skin->joints_count;
    if (mesh->joint_count > SK_MAX_JOINTS) {
        log_warn("model has %d joints; clamping to %d", mesh->joint_count, SK_MAX_JOINTS);
        mesh->joint_count = SK_MAX_JOINTS;
    }
    mesh->joint_nodes = (int *)calloc((size_t)mesh->joint_count, sizeof(int));
    mesh->inverse_bind = (sk_mat4_t *)calloc((size_t)mesh->joint_count, sizeof(sk_mat4_t));
    for (int j = 0; j < mesh->joint_count; j++) {
        mesh->joint_nodes[j] = node_index(g, skin->joints[j]);
        if (skin->inverse_bind_matrices) {
            cgltf_accessor_read_float(skin->inverse_bind_matrices, (cgltf_size)j,
                                      mesh->inverse_bind[j].m, 16);
        } else {
            mesh->inverse_bind[j] = sk_mat4_identity();
        }
    }
    mesh->has_skin = true;
}

static void parse_animations(sk_mesh_t *mesh, const cgltf_data *g)
{
    mesh->animation_count = (int)g->animations_count;
    if (mesh->animation_count == 0) return;
    mesh->animations = (sk_animation_t *)calloc((size_t)mesh->animation_count, sizeof(sk_animation_t));

    for (int a = 0; a < mesh->animation_count; a++) {
        const cgltf_animation *ga = &g->animations[a];
        sk_animation_t *anim = &mesh->animations[a];
        int cc = 0;

        anim->channels = (sk_anim_channel_t *)calloc(ga->channels_count, sizeof(sk_anim_channel_t));
        for (cgltf_size c = 0; c < ga->channels_count; c++) {
            const cgltf_animation_channel *gc = &ga->channels[c];
            const cgltf_animation_sampler *gs = gc->sampler;
            sk_anim_channel_t *ch = &anim->channels[cc];
            int comp;

            if (gc->target_path == cgltf_animation_path_type_translation) ch->path = 0;
            else if (gc->target_path == cgltf_animation_path_type_rotation) ch->path = 1;
            else if (gc->target_path == cgltf_animation_path_type_scale) ch->path = 2;
            else continue; /* skip weights/morph */

            ch->node = node_index(g, gc->target_node);
            ch->interp = (gs->interpolation == cgltf_interpolation_type_step) ? 1 : 0;
            ch->key_count = (int)gs->input->count;
            comp = (ch->path == 1) ? 4 : 3;

            ch->times = (float *)malloc((size_t)ch->key_count * sizeof(float));
            ch->values = (float *)malloc((size_t)ch->key_count * comp * sizeof(float));
            for (int k = 0; k < ch->key_count; k++) {
                cgltf_accessor_read_float(gs->input, (cgltf_size)k, &ch->times[k], 1);
                cgltf_accessor_read_float(gs->output, (cgltf_size)k, &ch->values[k * comp], comp);
                if (ch->times[k] > anim->duration) anim->duration = ch->times[k];
            }
            cc++;
        }
        anim->channel_count = cc;
    }
}

/* One material per glTF material, plus glTF's default material if a primitive
 * uses it. Textures are shared between materials that use the same image. */
static void load_materials(sk_mesh_t *mesh, const cgltf_data *g, const char *path)
{
    sk_gltf_textures_t cache = {.gltf = g, .path = path};
    bool uses_default = false;

    for (int p = 0; p < mesh->prim_count; p++) {
        uses_default = uses_default || mesh->prims[p].material == (int)g->materials_count;
    }
    mesh->material_count = (int)g->materials_count + (uses_default ? 1 : 0);
    if (mesh->material_count == 0) {
        return;
    }
    mesh->materials = (sk_handle_t *)calloc((size_t)mesh->material_count, sizeof(sk_handle_t));
    cache.images = (sk_gltf_image_t *)calloc(g->images_count + 1, sizeof(sk_gltf_image_t));
    if (mesh->materials == NULL || cache.images == NULL) {
        free(cache.images);
        mesh->material_count = 0;
        return;
    }
    for (int i = 0; i < mesh->material_count; i++) {
        mesh->materials[i] = create_gltf_material(&cache, i < (int)g->materials_count ? &g->materials[i] : NULL);
    }
    for (cgltf_size i = 0; i < g->images_count; i++) {
        sk_texture_release(cache.images[i].texture); /* materials hold what they use */
    }
    free(cache.images);
}

static bool load_model(sk_mesh_t *mesh, const unsigned char *data, int size, const char *path)
{
    cgltf_options options = {0};
    cgltf_data *g = NULL;
    int total = 0, idx = 0;

    if (cgltf_parse(&options, data, (cgltf_size)size, &g) != cgltf_result_success) return false;
    /* `path` lets buffers in files next to a .gltf load (sk_asset ensured them) */
    if (cgltf_load_buffers(&options, g, path) != cgltf_result_success) {
        log_error("model: buffers of %s couldn't be loaded", path != NULL ? path : "(memory)");
        cgltf_free(g);
        return false;
    }

    parse_skeleton(mesh, g);
    parse_animations(mesh, g);

    /* count triangle primitives across nodes that carry a mesh */
    for (cgltf_size n = 0; n < g->nodes_count; n++) {
        if (g->nodes[n].mesh) total += (int)g->nodes[n].mesh->primitives_count;
    }
    if (total == 0) {
        /* fall back to meshes not referenced by nodes */
        for (cgltf_size m = 0; m < g->meshes_count; m++) total += (int)g->meshes[m].primitives_count;
    }
    if (total == 0) { cgltf_free(g); return false; }
    mesh->prims = (sk_primitive_t *)calloc((size_t)total, sizeof(sk_primitive_t));
    if (mesh->prims == NULL) { cgltf_free(g); return false; }
    /* glTF's default material, for primitives without one, goes in the last slot */
    const int default_material = (int)g->materials_count;

    for (cgltf_size n = 0; n < g->nodes_count; n++) {
        const cgltf_node *node = &g->nodes[n];
        if (node->mesh == NULL) continue;
        bool node_skinned = (node->skin != NULL) && mesh->has_skin;
        sk_mat4_t node_world;
        cgltf_node_transform_world(node, node_world.m);
        for (cgltf_size p = 0; p < node->mesh->primitives_count; p++) {
            if (node->mesh->primitives[p].type != cgltf_primitive_type_triangles) continue;
            if (build_primitive(g, &node->mesh->primitives[p], node_skinned, &node_world,
                                default_material, &mesh->prims[idx])) idx++;
        }
    }
    if (idx == 0) { /* no node-meshes: load meshes directly (static) */
        for (cgltf_size m = 0; m < g->meshes_count; m++) {
            for (cgltf_size p = 0; p < g->meshes[m].primitives_count; p++) {
                if (g->meshes[m].primitives[p].type != cgltf_primitive_type_triangles) continue;
                if (build_primitive(g, &g->meshes[m].primitives[p], false, NULL, default_material,
                                    &mesh->prims[idx])) idx++;
            }
        }
    }
    mesh->prim_count = idx;
    if (idx > 0) load_materials(mesh, g, path);

    /* merged local-space AABB for broadphase/picking */
    mesh->lmin = (vec3_t){1e30f, 1e30f, 1e30f};
    mesh->lmax = (vec3_t){-1e30f, -1e30f, -1e30f};
    for (int p = 0; p < mesh->prim_count; p++) {
        if (mesh->prims[p].pmin.x < mesh->lmin.x) mesh->lmin.x = mesh->prims[p].pmin.x;
        if (mesh->prims[p].pmin.y < mesh->lmin.y) mesh->lmin.y = mesh->prims[p].pmin.y;
        if (mesh->prims[p].pmin.z < mesh->lmin.z) mesh->lmin.z = mesh->prims[p].pmin.z;
        if (mesh->prims[p].pmax.x > mesh->lmax.x) mesh->lmax.x = mesh->prims[p].pmax.x;
        if (mesh->prims[p].pmax.y > mesh->lmax.y) mesh->lmax.y = mesh->prims[p].pmax.y;
        if (mesh->prims[p].pmax.z > mesh->lmax.z) mesh->lmax.z = mesh->prims[p].pmax.z;
    }

    cgltf_free(g);
    return idx > 0;
}

/* ----------------------------------------------------------- animation ---- */

static void sample_channel(const sk_anim_channel_t *ch, float time, vec3_t *t, quat_t *r, vec3_t *s)
{
    int k0 = 0, k1 = 0, comp = (ch->path == 1) ? 4 : 3;
    float f = 0.0f;

    if (ch->key_count <= 0) return;
    if (time <= ch->times[0]) {
        k0 = k1 = 0;
    } else if (time >= ch->times[ch->key_count - 1]) {
        k0 = k1 = ch->key_count - 1;
    } else {
        for (int k = 0; k < ch->key_count - 1; k++) {
            if (time >= ch->times[k] && time < ch->times[k + 1]) {
                k0 = k; k1 = k + 1;
                float dt = ch->times[k1] - ch->times[k0];
                f = dt > 1e-8f ? (time - ch->times[k0]) / dt : 0.0f;
                break;
            }
        }
    }
    if (ch->interp == 1) f = 0.0f; /* step */

    const float *v0 = &ch->values[k0 * comp];
    const float *v1 = &ch->values[k1 * comp];
    if (ch->path == 0) {
        *t = sk_v3_lerp((vec3_t){v0[0], v0[1], v0[2]}, (vec3_t){v1[0], v1[1], v1[2]}, f);
    } else if (ch->path == 2) {
        *s = sk_v3_lerp((vec3_t){v0[0], v0[1], v0[2]}, (vec3_t){v1[0], v1[1], v1[2]}, f);
    } else {
        *r = sk_quat_slerp((quat_t){v0[0], v0[1], v0[2], v0[3]},
                           (quat_t){v1[0], v1[1], v1[2], v1[3]}, f);
    }
}

/* recursive global transform with per-call cache */
static sk_mat4_t global_of(sk_mesh_t *mesh, vec3_t *ct, quat_t *cr, vec3_t *cs,
                           sk_mat4_t *cache, bool *done, int i)
{
    sk_mat4_t local;
    if (done[i]) return cache[i];
    local = sk_mat4_compose(ct[i], cr[i], cs[i]);
    if (mesh->nodes[i].parent >= 0) {
        cache[i] = sk_mat4_mul(global_of(mesh, ct, cr, cs, cache, done, mesh->nodes[i].parent), local);
    } else {
        cache[i] = local;
    }
    done[i] = true;
    return cache[i];
}

SK_KEEP
bool sk_model_animate(sk_handle_t handle, float delta_seconds)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_mesh_t *mesh_ptr;
    sk_animation_t *anim;
    vec3_t *ct, *cs;
    quat_t *cr;
    sk_mat4_t *cache;
    bool *done;

    if (model_ptr == NULL) return false;
    mesh_ptr = resolve_mesh(model_ptr->mesh);
    if (mesh_ptr == NULL) return false;
    if (!mesh_ptr->has_skin || model_ptr->cur_anim < 0 || model_ptr->cur_anim >= mesh_ptr->animation_count) return false;
    anim = &mesh_ptr->animations[model_ptr->cur_anim];

    model_ptr->anim_time += delta_seconds * model_ptr->anim_speed;
    if (anim->duration > 0.0f) {
        if (model_ptr->anim_loop) {
            model_ptr->anim_time = fmodf(model_ptr->anim_time, anim->duration);
            if (model_ptr->anim_time < 0.0f) model_ptr->anim_time += anim->duration;
        } else if (model_ptr->anim_time > anim->duration) {
            model_ptr->anim_time = anim->duration;
        }
    }

    ct = (vec3_t *)malloc((size_t)mesh_ptr->node_count * sizeof(vec3_t));
    cr = (quat_t *)malloc((size_t)mesh_ptr->node_count * sizeof(quat_t));
    cs = (vec3_t *)malloc((size_t)mesh_ptr->node_count * sizeof(vec3_t));
    cache = (sk_mat4_t *)malloc((size_t)mesh_ptr->node_count * sizeof(sk_mat4_t));
    done = (bool *)calloc((size_t)mesh_ptr->node_count, sizeof(bool));

    for (int i = 0; i < mesh_ptr->node_count; i++) {
        ct[i] = mesh_ptr->nodes[i].t; cr[i] = mesh_ptr->nodes[i].r; cs[i] = mesh_ptr->nodes[i].s;
    }
    for (int c = 0; c < anim->channel_count; c++) {
        sk_anim_channel_t *ch = &anim->channels[c];
        if (ch->node < 0 || ch->node >= mesh_ptr->node_count) continue;
        sample_channel(ch, model_ptr->anim_time, &ct[ch->node], &cr[ch->node], &cs[ch->node]);
    }
    for (int j = 0; j < mesh_ptr->joint_count; j++) {
        int jn = mesh_ptr->joint_nodes[j];
        sk_mat4_t gjoint = global_of(mesh_ptr, ct, cr, cs, cache, done, jn);
        model_ptr->joint_matrices[j] = sk_mat4_mul(gjoint, mesh_ptr->inverse_bind[j]);
    }
    model_ptr->pose_version++;

    free(ct); free(cr); free(cs); free(cache); free(done);
    return true;
}

SK_KEEP int sk_model_get_animation_count(sk_handle_t handle)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_mesh_t *mesh_ptr = model_ptr ? resolve_mesh(model_ptr->mesh) : NULL;
    return mesh_ptr ? mesh_ptr->animation_count : 0;
}

SK_KEEP bool sk_model_set_animation(sk_handle_t handle, int animation_index)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    /* Stored as instance state regardless of the current mesh; sk_model_animate
     * applies it once a mesh with this clip is attached (range-guarded there),
     * so the selection survives a late/changed mesh. */
    model_ptr->cur_anim = animation_index;
    model_ptr->anim_time = 0.0f;
    return true;
}

SK_KEEP bool sk_model_set_animation_speed(sk_handle_t handle, float speed)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    model_ptr->anim_speed = speed;
    return true;
}

SK_KEEP bool sk_model_set_animation_loop(sk_handle_t handle, bool loop)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    model_ptr->anim_loop = loop;
    return true;
}

/* ------------------------------------------------ mesh resources ---------- */

static sk_mesh_t *resolve_mesh(sk_handle_t handle)
{
    uint16_t index = 0;
    if (!sk_handle_pool_resolve(&sk_mesh_pool, handle, &index)) {
        if (handle != 0) log_warn("Invalid mesh handle (%u)", (unsigned int)handle);
        return NULL;
    }
    return &sk_meshes[index];
}

static sk_model_t *resolve(sk_handle_t handle)
{
    uint16_t index = 0;
    if (!sk_handle_pool_resolve(&sk_model_pool, handle, &index)) {
        if (handle != 0) log_warn("Invalid model handle (%u)", (unsigned int)handle);
        return NULL;
    }
    return &sk_models[index];
}

static void free_mesh_data(sk_mesh_t *mesh)
{
    for (int p = 0; p < mesh->prim_count; p++) {
        sg_destroy_buffer(mesh->prims[p].vbuf);
        sg_destroy_buffer(mesh->prims[p].ibuf);
        free(mesh->prims[p].pick_positions);
        free(mesh->prims[p].pick_indices);
        free(mesh->prims[p].pick_joints);
        free(mesh->prims[p].pick_weights);
        free(mesh->prims[p].pick_uvs[0]);
        free(mesh->prims[p].pick_uvs[1]);
        free(mesh->prims[p].pick_alpha);
    }
    free(mesh->prims);
    for (int m = 0; m < mesh->material_count; m++) {
        sk_material_release(mesh->materials[m]);
    }
    free(mesh->materials);
    free_mesh_cpu(mesh);
}

static void retain_mesh(sk_handle_t mesh_handle)
{
    sk_mesh_t *mesh_ptr = resolve_mesh(mesh_handle);
    if (mesh_ptr != NULL) mesh_ptr->ref_count++;
}

static void release_mesh(sk_handle_t mesh_handle)
{
    sk_mesh_t *mesh_ptr = resolve_mesh(mesh_handle);
    if (mesh_ptr == NULL) return;
    if (mesh_ptr->ref_count > 0) mesh_ptr->ref_count--;
    if (mesh_ptr->ref_count == 0) {
        free_mesh_data(mesh_ptr);
        memset(mesh_ptr, 0, sizeof(*mesh_ptr));
        sk_handle_pool_free(&sk_mesh_pool, mesh_handle);
    }
}

static sk_handle_t find_mesh_by_path(const char *path)
{
    if (path == NULL || path[0] == '\0') return 0;
    for (uint16_t i = 1; i < MAX_MESHES; i++) {
        if (sk_mesh_occupied[i] && sk_meshes[i].has_path &&
            strcmp(sk_meshes[i].path, path) == 0) {
            return sk_handle_pool_handle_from_index(&sk_mesh_pool, i);
        }
    }
    return 0;
}

static sk_handle_t create_mesh(const unsigned char *data, int size, const char *path)
{
    sk_handle_t handle;
    uint16_t index = 0;
    sk_mesh_t mesh = {0};

    if (!load_model(&mesh, data, size, path)) {
        log_error("failed to load model");
        free_mesh_data(&mesh);
        return 0;
    }
    handle = sk_handle_pool_alloc(&sk_mesh_pool);
    if (handle == 0) {
        log_error("MAX_MESHES reached (%d)", MAX_MESHES);
        free_mesh_data(&mesh);
        return 0;
    }
    if (path != NULL && path[0] != '\0') {
        size_t n = strlen(path);
        if (n >= sizeof(mesh.path)) n = sizeof(mesh.path) - 1;
        memcpy(mesh.path, path, n);
        mesh.path[n] = '\0';
        mesh.has_path = true;
    }
    mesh.ref_count = 0; /* references are added by models and explicit ownership */
    sk_handle_pool_resolve(&sk_mesh_pool, handle, &index);
    sk_meshes[index] = mesh;
    return handle;
}

static sk_handle_t create_model(sk_handle_t mesh_handle)
{
    sk_handle_t handle;
    uint16_t index = 0;
    sk_model_t model = {0};

    /* mesh_handle may be 0 — create an empty model now and attach the mesh later
     * with sk_model_set_mesh(); draw/animate no-op until then. */
    handle = sk_handle_pool_alloc(&sk_model_pool);
    if (handle == 0) {
        log_error("MAX_MODELS reached (%d)", MAX_MODELS);
        return 0;
    }
    model.mesh = mesh_handle;
    model.scale = (vec3_t){1, 1, 1};
    model.visible = true;
    model.cur_anim = -1;
    model.anim_speed = 1.0f;
    model.anim_loop = true;
    for (int j = 0; j < SK_MAX_JOINTS; j++) model.joint_matrices[j] = sk_mat4_identity();
    retain_mesh(mesh_handle);
    sk_handle_pool_resolve(&sk_model_pool, handle, &index);
    sk_models[index] = model;
    return handle;
}

static unsigned char *read_file_bytes(const char *path, int *out_size)
{
    FILE *f;
    long size;
    unsigned char *bytes;

    *out_size = 0;
    if (path == NULL || (f = fopen(path, "rb")) == NULL) {
        return NULL; /* callers report it */
    }
    fseek(f, 0, SEEK_END); size = ftell(f); fseek(f, 0, SEEK_SET);
    if (size <= 0) { fclose(f); return NULL; }
    bytes = (unsigned char *)malloc((size_t)size);
    if (bytes == NULL) { fclose(f); return NULL; }
    if (fread(bytes, 1, (size_t)size, f) != (size_t)size) { free(bytes); fclose(f); return NULL; }
    fclose(f);
    *out_size = (int)size;
    return bytes;
}

/* --------------------------------------------- public API (mesh resource) - */

SK_KEEP
sk_handle_t sk_mesh_create(const char *path)
{
    sk_handle_t mesh = find_mesh_by_path(path);
    unsigned char *bytes;
    int size = 0;

    if (mesh != 0) { retain_mesh(mesh); return mesh; }
    bytes = read_file_bytes(path, &size);
    if (bytes == NULL) {
        log_error("failed to open model: %s", path != NULL ? path : "(null)");
        return 0;
    }
    mesh = create_mesh(bytes, size, path);
    free(bytes);
    if (mesh == 0) return 0;
    retain_mesh(mesh);
    return mesh;
}

SK_KEEP void sk_mesh_destroy(sk_handle_t mesh) { release_mesh(mesh); }

SK_KEEP int sk_mesh_get_material_count(sk_handle_t mesh)
{
    sk_mesh_t *mesh_ptr = resolve_mesh(mesh);
    return mesh_ptr != NULL ? mesh_ptr->material_count : 0;
}

SK_KEEP sk_handle_t sk_mesh_get_material(sk_handle_t mesh, int slot)
{
    sk_mesh_t *mesh_ptr = resolve_mesh(mesh);
    if (mesh_ptr == NULL || slot < 0 || slot >= mesh_ptr->material_count) {
        return 0;
    }
    return mesh_ptr->materials[slot];
}

/* --------------------------------------------- public API (model object) -- */

/* A drawable instance of a Mesh; adds its own reference to the mesh. */
SK_KEEP sk_handle_t sk_model_create(sk_handle_t mesh) { return create_model(mesh); }

/* Attach (or swap) the mesh resource on an existing model. Transform, tint,
 * visibility, and animation selection are retained, so a model created empty
 * picks them up the moment a mesh arrives. */
SK_KEEP bool sk_model_set_mesh(sk_handle_t handle, sk_handle_t mesh)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    if (model_ptr->mesh == mesh) return true;
    release_mesh(model_ptr->mesh); /* no-op when 0 */
    model_ptr->mesh = mesh;
    retain_mesh(mesh);             /* no-op when 0 */
    /* old skeleton no longer valid; animate() rebuilds these next tick */
    for (int j = 0; j < SK_MAX_JOINTS; j++) model_ptr->joint_matrices[j] = sk_mat4_identity();
    model_ptr->pose_version = 0; /* bind pose until animated */
    return true;
}

SK_KEEP bool sk_model_set_transform(sk_handle_t handle,
                                    float px, float py, float pz,
                                    float rx, float ry, float rz,
                                    float sx, float sy, float sz)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    model_ptr->position = (vec3_t){px, py, pz};
    model_ptr->rotation = (vec3_t){rx, ry, rz};
    model_ptr->scale = (vec3_t){sx, sy, sz};
    return true;
}

SK_KEEP bool sk_model_set_tint(sk_handle_t handle, sk_handle_t color)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    model_ptr->tint = color;
    return true;
}

static void set_material_slot(sk_model_t *model_ptr, int slot, sk_handle_t material)
{
    if (model_ptr->materials[slot] != material) {
        sk_material_retain(material); /* no-op for 0 */
        sk_material_release(model_ptr->materials[slot]);
        model_ptr->materials[slot] = material;
    }
}

SK_KEEP bool sk_model_set_material(sk_handle_t handle, int slot, sk_handle_t material)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    if (material != 0 && sk_material_get(material) == NULL) {
        log_warn("sk_model_set_material: invalid material handle (%u)", (unsigned int)material);
        return false;
    }
    if (slot == -1) {
        for (int m = 0; m < SK_MAX_MATERIAL_SLOTS; m++) set_material_slot(model_ptr, m, material);
        return true;
    }
    if (slot < 0 || slot >= SK_MAX_MATERIAL_SLOTS) {
        log_warn("sk_model_set_material: slot %d out of range (0..%d)", slot, SK_MAX_MATERIAL_SLOTS - 1);
        return false;
    }
    set_material_slot(model_ptr, slot, material);
    return true;
}

SK_KEEP sk_handle_t sk_model_get_material(sk_handle_t handle, int slot)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_mesh_t *mesh_ptr;
    if (model_ptr == NULL || slot < 0) return 0;
    if (slot < SK_MAX_MATERIAL_SLOTS && sk_material_get(model_ptr->materials[slot]) != NULL) {
        return model_ptr->materials[slot];
    }
    mesh_ptr = model_ptr->mesh != 0 ? resolve_mesh(model_ptr->mesh) : NULL;
    return mesh_ptr != NULL && slot < mesh_ptr->material_count ? mesh_ptr->materials[slot] : 0;
}

SK_KEEP bool sk_model_set_visible(sk_handle_t handle, bool visible)
{
    sk_model_t *model_ptr = resolve(handle);
    if (model_ptr == NULL) return false;
    model_ptr->visible = visible;
    return true;
}

SK_KEEP bool sk_model_is_visible(sk_handle_t handle)
{
    sk_model_t *model_ptr = resolve(handle);
    return model_ptr != NULL && model_ptr->visible;
}

SK_KEEP void sk_model_draw(sk_handle_t handle) { draw_immediate(handle); }

vec3_t sk_model_skin_position(const sk_mat4_t *joints, int joint_count, vec3_t p,
                              const uint8_t joint_index[4], const float weights[4])
{
    vec3_t out = {0.0f, 0.0f, 0.0f};
    for (int k = 0; k < 4; k++) {
        const float w = weights[k];
        const sk_mat4_t *m;
        if (w == 0.0f || joint_index[k] >= joint_count) {
            continue;
        }
        m = &joints[joint_index[k]];
        out.x += w * (m->m[0] * p.x + m->m[4] * p.y + m->m[8] * p.z + m->m[12]);
        out.y += w * (m->m[1] * p.x + m->m[5] * p.y + m->m[9] * p.z + m->m[13]);
        out.z += w * (m->m[2] * p.x + m->m[6] * p.y + m->m[10] * p.z + m->m[14]);
    }
    return out;
}

/* A texture coordinate wrapped into 0..1 like the GPU sampler does. */
static float wrap_coord(float c, sk_texture_wrap_t wrap)
{
    switch (wrap) {
        case SK_TEXTURE_WRAP_CLAMP:
            return c < 0.0f ? 0.0f : (c > 1.0f ? 1.0f : c);
        case SK_TEXTURE_WRAP_MIRROR: {
            float t = c - 2.0f * floorf(c * 0.5f); /* 0..2 */
            return t > 1.0f ? 2.0f - t : t;
        }
        default:
            return c - floorf(c);
    }
}

float sk_model_sample_alpha(const uint8_t *alpha, int width, int height, float u, float v,
                            sk_texture_wrap_t wrap_u, sk_texture_wrap_t wrap_v)
{
    int x, y;
    if (alpha == NULL || width <= 0 || height <= 0) {
        return 1.0f;
    }
    u = wrap_coord(u, wrap_u);
    v = wrap_coord(v, wrap_v);
    x = (int)(u * (float)width);
    y = (int)(v * (float)height);
    x = x >= width ? width - 1 : x;
    y = y >= height ? height - 1 : y;
    return (float)alpha[y * width + x] / 255.0f;
}

/* Pose the skinned primitives' pick geometry with the model's current joint
 * matrices, cached until the pose changes. Returns false when the bind pose
 * applies (not animated, or no skin), in which case pick_positions are used. */
static bool update_posed_geometry(sk_model_t *model_ptr, sk_mesh_t *mesh_ptr)
{
    int total = 0, offset = 0;
    const int joint_count = mesh_ptr->joint_count < SK_MAX_JOINTS ? mesh_ptr->joint_count : SK_MAX_JOINTS;

    if (model_ptr->pose_version == 0 || !mesh_ptr->has_skin) {
        return false;
    }
    if (model_ptr->posed_version == model_ptr->pose_version && model_ptr->posed_mesh == model_ptr->mesh) {
        return true;
    }
    for (int p = 0; p < mesh_ptr->prim_count; p++) {
        if (mesh_ptr->prims[p].skinned) {
            total += mesh_ptr->prims[p].pick_vertex_count;
        }
    }
    if (total > model_ptr->posed_capacity) {
        float *grown = (float *)realloc(model_ptr->posed_positions, (size_t)total * 3 * sizeof(float));
        if (grown == NULL) {
            return false;
        }
        model_ptr->posed_positions = grown;
        model_ptr->posed_capacity = total;
    }

    model_ptr->posed_min = (vec3_t){1e30f, 1e30f, 1e30f};
    model_ptr->posed_max = (vec3_t){-1e30f, -1e30f, -1e30f};
    for (int p = 0; p < mesh_ptr->prim_count; p++) {
        const sk_primitive_t *prim = &mesh_ptr->prims[p];
        if (!prim->skinned || prim->pick_joints == NULL || prim->pick_weights == NULL) {
            /* static primitive: its bind bounds are its bounds */
            vec3_t lo = prim->pmin, hi = prim->pmax;
            model_ptr->posed_min = (vec3_t){lo.x < model_ptr->posed_min.x ? lo.x : model_ptr->posed_min.x,
                                            lo.y < model_ptr->posed_min.y ? lo.y : model_ptr->posed_min.y,
                                            lo.z < model_ptr->posed_min.z ? lo.z : model_ptr->posed_min.z};
            model_ptr->posed_max = (vec3_t){hi.x > model_ptr->posed_max.x ? hi.x : model_ptr->posed_max.x,
                                            hi.y > model_ptr->posed_max.y ? hi.y : model_ptr->posed_max.y,
                                            hi.z > model_ptr->posed_max.z ? hi.z : model_ptr->posed_max.z};
            continue;
        }
        for (int v = 0; v < prim->pick_vertex_count; v++) {
            vec3_t bind = {prim->pick_positions[v * 3], prim->pick_positions[v * 3 + 1], prim->pick_positions[v * 3 + 2]};
            vec3_t posed = sk_model_skin_position(model_ptr->joint_matrices, joint_count, bind,
                                                  &prim->pick_joints[v * 4], &prim->pick_weights[v * 4]);
            float *dst = &model_ptr->posed_positions[(offset + v) * 3];
            dst[0] = posed.x; dst[1] = posed.y; dst[2] = posed.z;
            if (posed.x < model_ptr->posed_min.x) model_ptr->posed_min.x = posed.x;
            if (posed.y < model_ptr->posed_min.y) model_ptr->posed_min.y = posed.y;
            if (posed.z < model_ptr->posed_min.z) model_ptr->posed_min.z = posed.z;
            if (posed.x > model_ptr->posed_max.x) model_ptr->posed_max.x = posed.x;
            if (posed.y > model_ptr->posed_max.y) model_ptr->posed_max.y = posed.y;
            if (posed.z > model_ptr->posed_max.z) model_ptr->posed_max.z = posed.z;
        }
        offset += prim->pick_vertex_count;
    }
    model_ptr->posed_version = model_ptr->pose_version;
    model_ptr->posed_mesh = model_ptr->mesh;
    return true;
}

static bool model_bounds(sk_handle_t handle, vec3_t *lmin, vec3_t *lmax, sk_mat4_t *model_mat)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_mesh_t *mesh_ptr = model_ptr ? resolve_mesh(model_ptr->mesh) : NULL;
    if (model_ptr == NULL || mesh_ptr == NULL || !model_ptr->visible || mesh_ptr->prim_count == 0) {
        return false;
    }
    if (update_posed_geometry(model_ptr, mesh_ptr)) {
        *lmin = model_ptr->posed_min; /* animated: bounds of the current pose */
        *lmax = model_ptr->posed_max;
    } else {
        *lmin = mesh_ptr->lmin;
        *lmax = mesh_ptr->lmax;
    }
    *model_mat = sk_mat4_trs(model_ptr->position, model_ptr->rotation, model_ptr->scale);
    return true;
}

/* The material a model draws a primitive with: the model's override for the
 * primitive's slot, else the mesh's material, else glTF's default material. */
static const sk_material_t *prim_material(const sk_model_t *model_ptr, const sk_mesh_t *mesh_ptr,
                                          const sk_primitive_t *prim)
{
    static const sk_material_t fallback = {
        .shading = SK_MATERIAL_PBR,
        .alpha_cutoff = 0.5f,
        .base_color = {1.0f, 1.0f, 1.0f, 1.0f},
        .metallic = 1.0f,
        .roughness = 1.0f,
        .normal_scale = 1.0f,
        .occlusion_strength = 1.0f,
    };
    const sk_material_t *material = NULL;

    if (prim->material >= 0 && prim->material < SK_MAX_MATERIAL_SLOTS) {
        material = sk_material_get(model_ptr->materials[prim->material]);
    }
    if (material == NULL && prim->material >= 0 && prim->material < mesh_ptr->material_count) {
        material = sk_material_get(mesh_ptr->materials[prim->material]);
    }
    return material != NULL ? material : &fallback;
}

/* Whether a hit at barycentric (u, v) on triangle (i0, i1, i2) lands on a visible
 * part of the material. Opaque materials always do. MASK uses its cutoff; BLEND
 * counts as solid where the material is at least half opaque. Tint is ignored:
 * fading a model doesn't make it unpickable. */
static bool is_solid_at(const sk_primitive_t *prim, const sk_material_t *material, uint32_t i0, uint32_t i1,
                        uint32_t i2, float u, float v)
{
    const sk_material_texture_t *base = &material->textures[SK_MATERIAL_TEXTURE_BASE_COLOR];
    const float *uvs = prim->pick_uvs[base->texcoord == 1 ? 1 : 0];
    const float w0 = 1.0f - u - v;
    float alpha = material->base_color[3];
    const unsigned char *mask;
    int width, height;

    if (material->alpha_mode == SK_MATERIAL_ALPHA_OPAQUE) {
        return true;
    }

    if (prim->pick_alpha != NULL) {
        alpha *= prim->pick_alpha[i0] * w0 + prim->pick_alpha[i1] * u + prim->pick_alpha[i2] * v;
    }
    if (uvs != NULL && sk_texture_get_alpha_mask(base->texture, &mask, &width, &height)) {
        float m[6];
        const float su = uvs[i0 * 2] * w0 + uvs[i1 * 2] * u + uvs[i2 * 2] * v;
        const float sv = uvs[i0 * 2 + 1] * w0 + uvs[i1 * 2 + 1] * u + uvs[i2 * 2 + 1] * v;
        sk_material_uv_matrix(base, m);
        alpha *= sk_model_sample_alpha(mask, width, height, m[0] * su + m[1] * sv + m[2], m[3] * su + m[4] * sv + m[5],
                                       base->wrap_u, base->wrap_v);
    }
    return alpha >= (material->alpha_mode == SK_MATERIAL_ALPHA_MASK ? material->alpha_cutoff : 0.5f);
}

static bool model_pick(sk_handle_t handle, vec3_t origin, vec3_t dir, sk_pick_result_t *out)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_mesh_t *mesh_ptr = model_ptr ? resolve_mesh(model_ptr->mesh) : NULL;
    sk_mat4_t model_mat;
    sk_ray_t world, local;
    sk_ray_hit_t best = {0};
    vec3_t lmin, lmax;
    bool posed;
    int posed_offset = 0;

    if (out == NULL || model_ptr == NULL || mesh_ptr == NULL || !model_ptr->visible || mesh_ptr->prim_count == 0) {
        return false;
    }
    if (!model_bounds(handle, &lmin, &lmax, &model_mat)) {
        return false;
    }
    posed = update_posed_geometry(model_ptr, mesh_ptr);

    world.origin = origin;
    world.dir = dir;
    local = sk_pick_ray_to_local(model_mat, world);

    /* Narrow phase: ray/triangle against the geometry as drawn: the current pose
     * for animated skinned primitives, skipping see-through parts of MASK/BLEND
     * materials. */
    for (int p = 0; p < mesh_ptr->prim_count; p++) {
        sk_primitive_t *prim = &mesh_ptr->prims[p];
        const sk_material_t *material = prim_material(model_ptr, mesh_ptr, prim);
        const float *positions = prim->pick_positions;
        if (posed && prim->skinned && prim->pick_joints != NULL) {
            positions = &model_ptr->posed_positions[posed_offset * 3];
        }
        if (prim->skinned) {
            posed_offset += prim->pick_vertex_count;
        }
        if (positions == NULL || prim->pick_indices == NULL) {
            continue;
        }
        for (int k = 0; k + 2 < prim->index_count; k += 3) {
            uint32_t i0 = prim->pick_indices[k];
            uint32_t i1 = prim->pick_indices[k + 1];
            uint32_t i2 = prim->pick_indices[k + 2];
            vec3_t v0 = {positions[i0 * 3], positions[i0 * 3 + 1], positions[i0 * 3 + 2]};
            vec3_t v1 = {positions[i1 * 3], positions[i1 * 3 + 1], positions[i1 * 3 + 2]};
            vec3_t v2 = {positions[i2 * 3], positions[i2 * 3 + 1], positions[i2 * 3 + 2]};
            sk_ray_hit_t th = {0};
            if (sk_pick_ray_triangle(local, v0, v1, v2, &th) && (!best.hit || th.t < best.t) &&
                is_solid_at(prim, material, i0, i1, i2, th.u, th.v)) {
                best = th;
            }
        }
    }

    if (best.hit) {
        sk_pick_result_from_local(&best, world, model_mat, out);
    } else {
        *out = (sk_pick_result_t){0};
    }
    return true;
}

/* ---------------------------------------------------------- draw queue ---- */

/* Resolve a model that has something to draw. */
static sk_mesh_t *lookup_drawable(sk_handle_t handle, sk_model_t **model_out)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_mesh_t *mesh_ptr = model_ptr ? resolve_mesh(model_ptr->mesh) : NULL;
    if (model_ptr == NULL || mesh_ptr == NULL || !model_ptr->visible || mesh_ptr->prim_count == 0) {
        return NULL;
    }
    *model_out = model_ptr;
    return mesh_ptr;
}

static color_t model_tint(const sk_model_t *model_ptr)
{
    return sk_color_get(model_ptr->tint != 0 ? model_ptr->tint : 0); /* 0 -> white */
}

/* A primitive is transparent if its material blends, or if the model's tint
 * makes it translucent (e.g. fading a model out). */
static bool is_blended(color_t tint, const sk_material_t *material)
{
    return material->alpha_mode == SK_MATERIAL_ALPHA_BLEND || tint.a < 1.0f;
}

static vec3_t prim_center(const sk_primitive_t *prim)
{
    return (vec3_t){(prim->pmin.x + prim->pmax.x) * 0.5f,
                    (prim->pmin.y + prim->pmax.y) * 0.5f,
                    (prim->pmin.z + prim->pmax.z) * 0.5f};
}

static void log_queue_full(void)
{
    if (!sk_model_queue_full_logged) {
        log_warn("model: draw queue full (%d placements / %d primitives per frame)",
                 MAX_MODEL_DRAWS, MAX_MODEL_ITEMS);
        sk_model_queue_full_logged = true;
    }
}

/* Capture the model's matrices and tint for this frame. Consecutive submissions
 * of the same model reuse one placement. Returns the placement index or -1. */
static int begin_draw(sk_handle_t handle, sk_model_t *model_ptr)
{
    sk_camera3d_t cam;
    sk_mat4_t model_mat, view, proj;
    float aspect;
    sk_model_draw_t *e;
    vec2_t target_size;

    const int light_env = sk_light_env_current();
    const sk_light_env_t *env = sk_light_env_get(light_env);
    sk_mesh_t *mesh_ptr = resolve_mesh(model_ptr->mesh);

    if (sk_model_draw_count > 0 && sk_model_draws[sk_model_draw_count - 1].model == handle &&
        sk_model_draws[sk_model_draw_count - 1].light_env == light_env &&
        sk_model_draws[sk_model_draw_count - 1].pass == sk_render_current_pass()) {
        return sk_model_draw_count - 1;
    }
    if (sk_model_draw_count >= MAX_MODEL_DRAWS) {
        log_queue_full();
        return -1;
    }
    if (!sk_camera3d_get_active_data(&cam)) {
        return -1;
    }

    target_size = sk_render_target_size(); /* the screen, or the render target being drawn into */
    aspect = target_size.y > 0.0f ? target_size.x / target_size.y : 1.0f;
    model_mat = sk_mat4_trs(model_ptr->position, model_ptr->rotation, model_ptr->scale);
    view = sk_camera3d_view(&cam);
    proj = sk_camera3d_projection(&cam, aspect);

    e = &sk_model_draws[sk_model_draw_count];
    e->model = handle;
    e->pass = sk_render_current_pass();
    e->mvp = sk_mat4_mul(sk_mat4_mul(proj, view), model_mat);
    e->model_mat = model_mat;
    e->model_view = sk_mat4_mul(view, model_mat);
    e->normal_mat = sk_mat4_transpose(sk_mat4_inverse(model_mat));
    e->camera_pos = cam.position;
    e->tint = model_tint(model_ptr);

    /* choose this placement's lights once, from its world bounds */
    e->light_env = env != NULL ? light_env : -1;
    e->light_count = 0;
    if (env != NULL && mesh_ptr != NULL) {
        vec3_t wmin, wmax;
        sk_pick_world_aabb(mesh_ptr->lmin, mesh_ptr->lmax, model_mat, &wmin, &wmax);
        e->light_count = sk_light_select(env, wmin, wmax, e->lights, SK_MAX_DRAW_LIGHTS);
    }
    return sk_model_draw_count++;
}

static bool push_item(int draw, int prim, bool blended)
{
    if (sk_model_item_count >= MAX_MODEL_ITEMS) {
        log_queue_full();
        return false;
    }
    sk_model_items[sk_model_item_count++] = (sk_model_item_t){
        .draw = draw,
        .prim = prim,
        .blended = blended,
    };
    return true;
}

/* Farthest first. */
static int compare_blend_prims(const void *a, const void *b)
{
    float da = ((const sk_blend_prim_t *)a)->depth;
    float db = ((const sk_blend_prim_t *)b)->depth;
    return (da < db) - (da > db);
}

/* sk_model_draw(): opaque primitives, then this model's transparent primitives
 * back to front. Not sorted against other drawables (use a scene for that). */
static void draw_immediate(sk_handle_t handle)
{
    sk_model_t *model_ptr = NULL;
    sk_mesh_t *mesh_ptr = lookup_drawable(handle, &model_ptr);
    int draw, first, blend_count = 0;

    if (mesh_ptr == NULL || (draw = begin_draw(handle, model_ptr)) < 0) {
        return;
    }
    first = sk_model_item_count;
    for (int p = 0; p < mesh_ptr->prim_count; p++) {
        sk_primitive_t *prim = &mesh_ptr->prims[p];
        if (!is_blended(sk_model_draws[draw].tint, prim_material(model_ptr, mesh_ptr, prim))) {
            push_item(draw, p, false);
        } else if (blend_count < MAX_BLEND_PRIMS) {
            sk_blend_prims[blend_count++] = (sk_blend_prim_t){
                .prim = p,
                .depth = -sk_mat4_mul_point(sk_model_draws[draw].model_view, prim_center(prim)).z,
            };
        }
    }
    qsort(sk_blend_prims, (size_t)blend_count, sizeof(sk_blend_prims[0]), compare_blend_prims);
    for (int b = 0; b < blend_count; b++) {
        push_item(draw, sk_blend_prims[b].prim, true);
    }
    sk_render_submit_models(first, sk_model_item_count - first);
}

/* Scene opaque pass. */
static void draw_opaque(sk_handle_t handle)
{
    sk_model_t *model_ptr = NULL;
    sk_mesh_t *mesh_ptr = lookup_drawable(handle, &model_ptr);
    color_t tint;
    int draw = -1, first = sk_model_item_count;

    if (mesh_ptr == NULL) {
        return;
    }
    tint = model_tint(model_ptr);
    for (int p = 0; p < mesh_ptr->prim_count; p++) {
        if (is_blended(tint, prim_material(model_ptr, mesh_ptr, &mesh_ptr->prims[p]))) {
            continue;
        }
        if (draw < 0 && (draw = begin_draw(handle, model_ptr)) < 0) {
            return;
        }
        push_item(draw, p, false);
    }
    sk_render_submit_models(first, sk_model_item_count - first);
}

/* Scene transparent pass: one item per transparent primitive. */
static int collect_transparent(sk_handle_t handle, const sk_camera3d_t *cam,
                               sk_transparent_item_t *out, int max_items)
{
    sk_model_t *model_ptr = NULL;
    sk_mesh_t *mesh_ptr = lookup_drawable(handle, &model_ptr);
    color_t tint;
    sk_mat4_t model_mat;
    int count = 0;

    if (mesh_ptr == NULL) {
        return 0;
    }
    tint = model_tint(model_ptr);
    model_mat = sk_mat4_trs(model_ptr->position, model_ptr->rotation, model_ptr->scale);
    for (int p = 0; p < mesh_ptr->prim_count && count < max_items; p++) {
        const sk_primitive_t *prim = &mesh_ptr->prims[p];
        if (!is_blended(tint, prim_material(model_ptr, mesh_ptr, prim))) {
            continue;
        }
        out[count++] = (sk_transparent_item_t){
            .handle = handle,
            .part = p,
            .depth = sk_scene_view_depth(cam, sk_mat4_mul_point(model_mat, prim_center(prim))),
        };
    }
    return count;
}

static void draw_transparent(sk_handle_t handle, int part)
{
    sk_model_t *model_ptr = NULL;
    sk_mesh_t *mesh_ptr = lookup_drawable(handle, &model_ptr);
    int draw, first = sk_model_item_count;

    if (mesh_ptr == NULL || part < 0 || part >= mesh_ptr->prim_count ||
        (draw = begin_draw(handle, model_ptr)) < 0) {
        return;
    }
    if (push_item(draw, part, true)) {
        sk_render_submit_models(first, 1);
    }
}

static void apply_fs(const sk_model_draw_t *e, const sk_material_t *material)
{
    fs_params_t fsp;
    const sk_light_env_t *env = sk_light_env_get(e->light_env);
    const bool lit = env != NULL && material->shading == SK_MATERIAL_PBR;

    memset(&fsp, 0, sizeof(fsp));
    /* tint is an sRGB color like any color handle; alpha is linear */
    fsp.u_base_color[0] = sk_srgb_to_linear(e->tint.r) * material->base_color[0];
    fsp.u_base_color[1] = sk_srgb_to_linear(e->tint.g) * material->base_color[1];
    fsp.u_base_color[2] = sk_srgb_to_linear(e->tint.b) * material->base_color[2];
    fsp.u_base_color[3] = e->tint.a * material->base_color[3];
    fsp.u_emissive[0] = material->emissive[0];
    fsp.u_emissive[1] = material->emissive[1];
    fsp.u_emissive[2] = material->emissive[2];
    /* without a normal map the flat default texture must not tilt the normal */
    fsp.u_emissive[3] = material->textures[SK_MATERIAL_TEXTURE_NORMAL].texture != 0 ? material->normal_scale : 0.0f;
    fsp.u_pbr[0] = material->metallic;
    fsp.u_pbr[1] = material->roughness;
    fsp.u_pbr[2] = material->occlusion_strength;
    fsp.u_pbr[3] = lit ? 1.0f : 0.0f;
    fsp.u_material[0] = material->alpha_mode == SK_MATERIAL_ALPHA_MASK ? material->alpha_cutoff : 0.0f;
    fsp.u_camera_pos[0] = e->camera_pos.x;
    fsp.u_camera_pos[1] = e->camera_pos.y;
    fsp.u_camera_pos[2] = e->camera_pos.z;
    for (int t = 0; t < SK_MATERIAL_TEXTURE_COUNT; t++) {
        float m[6];
        sk_material_uv_matrix(&material->textures[t], m);
        if (sk_texture_is_flipped(material->textures[t].texture)) { /* render target stored bottom-up */
            m[3] = -m[3];
            m[4] = -m[4];
            m[5] = 1.0f - m[5];
        }
        fsp.u_uv_row0[t][0] = m[0];
        fsp.u_uv_row0[t][1] = m[1];
        fsp.u_uv_row0[t][2] = m[2];
        fsp.u_uv_row0[t][3] = (float)material->textures[t].texcoord;
        fsp.u_uv_row1[t][0] = m[3];
        fsp.u_uv_row1[t][1] = m[4];
        fsp.u_uv_row1[t][2] = m[5];
    }

    if (lit) {
        fsp.u_ambient[0] = env->ambient.x;
        fsp.u_ambient[1] = env->ambient.y;
        fsp.u_ambient[2] = env->ambient.z;
        fsp.u_material[1] = (float)e->light_count;
        for (int i = 0; i < e->light_count; i++) {
            const sk_scene_light_t *light = &env->lights[e->lights[i]];
            fsp.u_light_pos_range[i][0] = light->position.x;
            fsp.u_light_pos_range[i][1] = light->position.y;
            fsp.u_light_pos_range[i][2] = light->position.z;
            fsp.u_light_pos_range[i][3] = light->range;
            fsp.u_light_dir_type[i][0] = light->direction.x;
            fsp.u_light_dir_type[i][1] = light->direction.y;
            fsp.u_light_dir_type[i][2] = light->direction.z;
            fsp.u_light_dir_type[i][3] = (float)light->type;
            fsp.u_light_radiance[i][0] = light->radiance.x;
            fsp.u_light_radiance[i][1] = light->radiance.y;
            fsp.u_light_radiance[i][2] = light->radiance.z;
            fsp.u_light_spot[i][0] = light->cos_inner;
            fsp.u_light_spot[i][1] = light->cos_outer;
        }
    }
    sg_apply_uniforms(UB_fs_params, &(sg_range){.ptr = &fsp, .size = sizeof(fsp)});
}

static sg_view texture_view(const sk_material_texture_t *texture, sg_view fallback)
{
    sg_view view = fallback;
    if (texture->texture != 0) {
        sk_texture_get_binding(texture->texture, &view, NULL, NULL, NULL);
    }
    return view;
}

static sg_wrap sampler_wrap(sk_texture_wrap_t wrap)
{
    switch (wrap) {
        case SK_TEXTURE_WRAP_CLAMP: return SG_WRAP_CLAMP_TO_EDGE;
        case SK_TEXTURE_WRAP_MIRROR: return SG_WRAP_MIRRORED_REPEAT;
        default: return SG_WRAP_REPEAT;
    }
}

static sg_sampler texture_sampler(const sk_material_texture_t *texture)
{
    const int u = texture->wrap_u >= 0 && texture->wrap_u < 3 ? (int)texture->wrap_u : 0;
    const int v = texture->wrap_v >= 0 && texture->wrap_v < 3 ? (int)texture->wrap_v : 0;
    const int nearest = texture->filter == SK_TEXTURE_FILTER_NEAREST ? 1 : 0;
    const int mipmaps = texture->mipmaps ? 1 : 0;
    sg_sampler *smp = &sk_model_samplers[u][v][nearest][mipmaps];

    if (smp->id == SG_INVALID_ID) {
        const sg_filter filter = nearest ? SG_FILTER_NEAREST : SG_FILTER_LINEAR;
        *smp = sg_make_sampler(&(sg_sampler_desc){
            .min_filter = filter,
            .mag_filter = filter,
            .mipmap_filter = filter,
            .max_lod = mipmaps ? 1000.0f : 0.0f, /* 0: base level only */
            .wrap_u = sampler_wrap(texture->wrap_u),
            .wrap_v = sampler_wrap(texture->wrap_v),
        });
    }
    return *smp;
}

static void draw_primitive(const sk_model_draw_t *e, const sk_model_t *model_ptr, const sk_mesh_t *mesh_ptr,
                           const sk_primitive_t *prim, bool blended, sg_pipeline *cur_pip)
{
    const sk_material_t *material = prim_material(model_ptr, mesh_ptr, prim);
    const sk_material_texture_t *textures = material->textures;
    sg_pipeline pip = sk_pips[prim->skinned ? 1 : 0][blended ? 1 : 0][material->double_sided ? 1 : 0];
    if (pip.id != cur_pip->id) {
        sg_apply_pipeline(pip);
        *cur_pip = pip;
    }

    if (prim->skinned) {
        vs_skin_params_t vsp;
        memcpy(vsp.mvp, e->mvp.m, sizeof(vsp.mvp));
        memcpy(vsp.model, e->model_mat.m, sizeof(vsp.model));
        memcpy(vsp.normal_mat, e->normal_mat.m, sizeof(vsp.normal_mat));
        for (int j = 0; j < SK_MAX_JOINTS; j++) {
            memcpy(vsp.joints_mat[j], model_ptr->joint_matrices[j].m, 16 * sizeof(float));
        }
        sg_apply_uniforms(UB_vs_skin_params, &(sg_range){.ptr = &vsp, .size = sizeof(vsp)});
    } else {
        vs_params_t vsp;
        memcpy(vsp.mvp, e->mvp.m, sizeof(vsp.mvp));
        memcpy(vsp.model, e->model_mat.m, sizeof(vsp.model));
        memcpy(vsp.normal_mat, e->normal_mat.m, sizeof(vsp.normal_mat));
        sg_apply_uniforms(UB_vs_params, &(sg_range){.ptr = &vsp, .size = sizeof(vsp)});
    }

    sg_apply_bindings(&(sg_bindings){
        .vertex_buffers[0] = prim->vbuf,
        .index_buffer = prim->ibuf,
        .views[VIEW_base_color_tex] = texture_view(&textures[SK_MATERIAL_TEXTURE_BASE_COLOR], sk_model_white_view),
        .views[VIEW_metallic_roughness_tex] =
            texture_view(&textures[SK_MATERIAL_TEXTURE_METALLIC_ROUGHNESS], sk_model_white_view),
        .views[VIEW_normal_tex] = texture_view(&textures[SK_MATERIAL_TEXTURE_NORMAL], sk_model_flat_normal_view),
        .views[VIEW_occlusion_tex] = texture_view(&textures[SK_MATERIAL_TEXTURE_OCCLUSION], sk_model_white_view),
        .views[VIEW_emissive_tex] = texture_view(&textures[SK_MATERIAL_TEXTURE_EMISSIVE], sk_model_white_view),
        .samplers[SMP_base_color_smp] = texture_sampler(&textures[SK_MATERIAL_TEXTURE_BASE_COLOR]),
        .samplers[SMP_metallic_roughness_smp] = texture_sampler(&textures[SK_MATERIAL_TEXTURE_METALLIC_ROUGHNESS]),
        .samplers[SMP_normal_smp] = texture_sampler(&textures[SK_MATERIAL_TEXTURE_NORMAL]),
        .samplers[SMP_occlusion_smp] = texture_sampler(&textures[SK_MATERIAL_TEXTURE_OCCLUSION]),
        .samplers[SMP_emissive_smp] = texture_sampler(&textures[SK_MATERIAL_TEXTURE_EMISSIVE]),
    });
    apply_fs(e, material);
    sg_draw(0, prim->index_count, 1);
}

void sk_model_draw_items(int first, int count)
{
    sg_pipeline cur_pip = {0}; /* sokol_gl may have changed the pipeline since last time */

    for (int i = first; i < first + count && i < sk_model_item_count; i++) {
        const sk_model_item_t *item = &sk_model_items[i];
        sk_model_draw_t *e = &sk_model_draws[item->draw];
        sk_model_t *model_ptr = resolve(e->model);
        sk_mesh_t *mesh_ptr = model_ptr ? resolve_mesh(model_ptr->mesh) : NULL;
        if (mesh_ptr == NULL || item->prim >= mesh_ptr->prim_count) {
            continue; /* destroyed or re-meshed after it was queued */
        }
        draw_primitive(e, model_ptr, mesh_ptr, &mesh_ptr->prims[item->prim], item->blended, &cur_pip);
    }
}

void sk_model_end_frame(void)
{
    sk_model_draw_count = 0;
    sk_model_item_count = 0;
}

static void free_mesh_cpu(sk_mesh_t *mesh)
{
    for (int a = 0; a < mesh->animation_count; a++) {
        for (int c = 0; c < mesh->animations[a].channel_count; c++) {
            free(mesh->animations[a].channels[c].times);
            free(mesh->animations[a].channels[c].values);
        }
        free(mesh->animations[a].channels);
    }
    free(mesh->animations);
    free(mesh->nodes);
    free(mesh->joint_nodes);
    free(mesh->inverse_bind);
}

SK_KEEP void sk_model_destroy(sk_handle_t handle)
{
    sk_model_t *model_ptr = resolve(handle);
    sk_handle_t mesh;
    if (model_ptr == NULL) return;
    mesh = model_ptr->mesh;
    for (int m = 0; m < SK_MAX_MATERIAL_SLOTS; m++) {
        sk_material_release(model_ptr->materials[m]); /* no-op for 0 */
    }
    free(model_ptr->posed_positions);
    memset(model_ptr, 0, sizeof(*model_ptr));
    sk_handle_pool_free(&sk_model_pool, handle);
    release_mesh(mesh); /* frees the mesh once its last model/owner is gone */
}

/* sk_asset: the buffer and image files a glTF file references. */
static void list_gltf_dependencies(const unsigned char *data, int size, sk_asset_add_dependency_fn add,
                                   void *context)
{
    cgltf_options options = {0};
    cgltf_data *g = NULL;

    if (cgltf_parse(&options, data, (cgltf_size)size, &g) != cgltf_result_success) {
        return; /* sk_mesh_create reports the broken file */
    }
    for (cgltf_size i = 0; i < g->buffers_count; i++) {
        if (g->buffers[i].uri != NULL) add(g->buffers[i].uri, true, context);
    }
    for (cgltf_size i = 0; i < g->images_count; i++) {
        /* optional: a missing image gets the placeholder texture */
        if (g->images[i].uri != NULL && g->images[i].buffer_view == NULL) add(g->images[i].uri, false, context);
    }
    cgltf_free(g);
}

void sk_model_init(void)
{
    static const unsigned char white[4] = {255, 255, 255, 255};
    static const unsigned char flat_normal[4] = {128, 128, 255, 255};
    sg_pipeline_desc base;

    memset(sk_models, 0, sizeof(sk_models));
    memset(sk_meshes, 0, sizeof(sk_meshes));
    sk_model_end_frame();
    sk_handle_pool_init(&sk_model_pool, SK_HANDLE_KIND_MODEL, MAX_MODELS,
                        sk_model_free_indices, MAX_MODELS,
                        sk_model_generations, sk_model_occupied);
    sk_handle_pool_init(&sk_mesh_pool, SK_HANDLE_KIND_MESH, MAX_MESHES,
                        sk_mesh_free_indices, MAX_MESHES,
                        sk_mesh_generations, sk_mesh_occupied);

    sk_shd_static = make_static_shader();
    sk_shd_skinned = make_skinned_shader();

    base = (sg_pipeline_desc){
        .index_type = SG_INDEXTYPE_UINT32,
        .face_winding = SG_FACEWINDING_CCW,
        .depth = {.compare = SG_COMPAREFUNC_LESS_EQUAL, .write_enabled = true},
    };

    for (int skinned = 0; skinned < 2; skinned++) {
        for (int blended = 0; blended < 2; blended++) {
            for (int double_sided = 0; double_sided < 2; double_sided++) {
                sg_pipeline_desc d = base;
                d.shader = skinned ? sk_shd_skinned : sk_shd_static;
                d.layout.attrs[0].format = SG_VERTEXFORMAT_FLOAT3;
                d.layout.attrs[1].format = SG_VERTEXFORMAT_FLOAT3;
                d.layout.attrs[2].format = SG_VERTEXFORMAT_FLOAT2; /* texcoord0 */
                d.layout.attrs[3].format = SG_VERTEXFORMAT_FLOAT2; /* texcoord1 */
                d.layout.attrs[4].format = SG_VERTEXFORMAT_FLOAT4; /* tangent */
                d.layout.attrs[5].format = SG_VERTEXFORMAT_FLOAT4; /* color0 */
                if (skinned) {
                    d.layout.attrs[6].format = SG_VERTEXFORMAT_FLOAT4; /* joints */
                    d.layout.attrs[7].format = SG_VERTEXFORMAT_FLOAT4; /* weights */
                }
                d.cull_mode = double_sided ? SG_CULLMODE_NONE : SG_CULLMODE_BACK;
                if (blended) {
                    d.depth.write_enabled = false;
                    d.colors[0].blend = (sg_blend_state){
                        .enabled = true,
                        .src_factor_rgb = SG_BLENDFACTOR_SRC_ALPHA,
                        .dst_factor_rgb = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
                        .src_factor_alpha = SG_BLENDFACTOR_ONE,
                        .dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
                    };
                }
                d.label = "sk-model-pip";
                sk_pips[skinned][blended][double_sided] = sg_make_pipeline(&d);
            }
        }
    }

    sk_model_white_img = sg_make_image(&(sg_image_desc){
        .width = 1, .height = 1, .pixel_format = SG_PIXELFORMAT_RGBA8,
        .data.mip_levels[0] = {.ptr = white, .size = sizeof(white)}});
    sk_model_white_view = sg_make_view(&(sg_view_desc){.texture.image = sk_model_white_img});
    sk_model_flat_normal_img = sg_make_image(&(sg_image_desc){
        .width = 1, .height = 1, .pixel_format = SG_PIXELFORMAT_RGBA8,
        .data.mip_levels[0] = {.ptr = flat_normal, .size = sizeof(flat_normal)}});
    sk_model_flat_normal_view = sg_make_view(&(sg_view_desc){.texture.image = sk_model_flat_normal_img});

    sk_scene_register_passes(SK_HANDLE_KIND_MODEL, draw_opaque, collect_transparent, draw_transparent);
    sk_scene_register_bounds(SK_HANDLE_KIND_MODEL, model_bounds);
    sk_scene_register_pick(SK_HANDLE_KIND_MODEL, model_pick);
    sk_asset_register_dependencies(".gltf", list_gltf_dependencies);
    sk_asset_register_dependencies(".glb", list_gltf_dependencies);
}

void sk_model_deinit(void)
{
    for (uint16_t i = 1; i < MAX_MODELS; i++) {
        if (sk_model_occupied[i]) {
            sk_handle_t h = sk_handle_pool_handle_from_index(&sk_model_pool, i);
            sk_model_destroy(h);
        }
    }
    /* drop any meshes created explicitly (preloaded) with no live models */
    for (uint16_t i = 1; i < MAX_MESHES; i++) {
        if (sk_mesh_occupied[i]) {
            sk_mesh_t *mesh = &sk_meshes[i];
            free_mesh_data(mesh);
            memset(mesh, 0, sizeof(*mesh));
        }
    }
    sg_destroy_view(sk_model_white_view);
    sg_destroy_view(sk_model_flat_normal_view);
    sg_destroy_image(sk_model_flat_normal_img);
    sg_destroy_image(sk_model_white_img);
    for (int i = 0; i < 3 * 3 * 2 * 2; i++) {
        sg_sampler *smp = &((sg_sampler *)sk_model_samplers)[i];
        if (smp->id != SG_INVALID_ID) sg_destroy_sampler(*smp);
        *smp = (sg_sampler){0};
    }
    for (int skinned = 0; skinned < 2; skinned++) {
        for (int blended = 0; blended < 2; blended++) {
            for (int double_sided = 0; double_sided < 2; double_sided++) {
                sg_destroy_pipeline(sk_pips[skinned][blended][double_sided]);
            }
        }
    }
    sg_destroy_shader(sk_shd_static);
    sg_destroy_shader(sk_shd_skinned);
    sk_handle_pool_reset(&sk_model_pool);
    sk_handle_pool_reset(&sk_mesh_pool);
}
